### ISSUE TITLE
libcudart version problem

### ISSUE THREAD

**Issue by GaoQiyu** [NVIDIAGameWorks/kaolin#103]
I compile kaolin with cudatoolkit10.0 and pytorch1.3+cu10.0 and it works：
but when  i  try to import kaolin in python, it pint like this：

Python 3.7.0 (default, Jun 28 2018, 13:15:42) 
[GCC 7.2.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import kaolin
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/gaoqiyu/anaconda3/lib/python3.7/site-packages/kaolin-0.2.0-py3.7-linux-x86_64.egg/kaolin/__init__.py", line 17, in <module>
  File "/home/gaoqiyu/anaconda3/lib/python3.7/site-packages/kaolin-0.2.0-py3.7-linux-x86_64.egg/kaolin/conversions/__init__.py", line 1, in <module>
  File "/home/gaoqiyu/anaconda3/lib/python3.7/site-packages/kaolin-0.2.0-py3.7-linux-x86_64.egg/kaolin/conversions/meshconversions.py", line 22, in <module>
  File "/home/gaoqiyu/anaconda3/lib/python3.7/site-packages/kaolin-0.2.0-py3.7-linux-x86_64.egg/kaolin/metrics/__init__.py", line 2, in <module>
  File "/home/gaoqiyu/anaconda3/lib/python3.7/site-packages/kaolin-0.2.0-py3.7-linux-x86_64.egg/kaolin/metrics/point.py", line 17, in <module>
  File "/home/gaoqiyu/anaconda3/lib/python3.7/site-packages/kaolin-0.2.0-py3.7-linux-x86_64.egg/kaolin/cuda/sided_distance.py", line 7, in <module>
  File "/home/gaoqiyu/anaconda3/lib/python3.7/site-packages/kaolin-0.2.0-py3.7-linux-x86_64.egg/kaolin/cuda/sided_distance.py", line 6, in __bootstrap__
  File "/home/gaoqiyu/anaconda3/lib/python3.7/imp.py", line 343, in load_dynamic
    return _load(spec)
ImportError: libcudart.so.10.1: cannot open shared object file: No such file or directory

I dont have cuda10.1 on my device
what should I do？

**Comment by Caenorst** [comment]
Hi, thank you for using Kaolin! The library went through a major rewrite with the version [0.9.0](https://github.com/NVIDIAGameWorks/kaolin/releases/tag/v0.9.0), and only the core library components we can thoroughly test and maintain are now part of this repository. Please refer to our latest documentation:
[https://kaolin.readthedocs.io/en/latest/](https://kaolin.readthedocs.io/en/latest/)

Closing the bug as it is no longer relevant to this repo.
