### ISSUE TITLE
Problem building the documentation

### ISSUE THREAD

**Issue by OshriHalimi** [NVIDIAGameWorks/kaolin#107]
Thank you for publishing this great library!
I followed all the instructions and managed to install the library as well as running the Unittest.
However, trying to build the documentation I get the following error:

`Running Sphinx v2.2.0
loading intersphinx inventory from https://docs.python.org/3/objects.inv...
loading intersphinx inventory from http://docs.scipy.org/doc/numpy/objects.inv...
intersphinx inventory has moved: http://docs.scipy.org/doc/numpy/objects.inv -> https://docs.scipy.org/doc/numpy/objects.inv
loading intersphinx inventory from http://pytorch.org/docs/master/objects.inv...
intersphinx inventory has moved: http://pytorch.org/docs/master/objects.inv -> https://pytorch.org/docs/master/objects.inv
building [mo]: targets for 0 po files that are out of date
building [html]: targets for 40 source files that are out of date
updating environment: [new config] 40 added, 0 changed, 0 removed
WARNING: autodoc: failed to import class 'DifferentiableRenderer' from module 'graphics'; the following exception was raised:
Traceback (most recent call last):
  File "/home/smosesli/anaconda3/envs/kaolin/lib/python3.6/site-packages/Sphinx-2.2.0-py3.6.egg/sphinx/ext/autodoc/importer.py", line 32, in import_module
    return importlib.import_module(modname)
  File "/home/smosesli/anaconda3/envs/kaolin/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/smosesli/externals/kaolin/kaolin/graphics/__init__.py", line 8, in <module>
    from .DIBRenderer import DIBRenderer
  File "/home/smosesli/externals/kaolin/kaolin/graphics/DIBRenderer.py", line 38, in <module>
    from .dib_renderer.renderer import Renderer as DIBRenderer
  File "/home/smosesli/externals/kaolin/kaolin/graphics/dib_renderer/renderer/__init__.py", line 1, in <module>
    from .base import *
  File "/home/smosesli/externals/kaolin/kaolin/graphics/dib_renderer/renderer/base.py", line 24, in <module>
    from ....mathutils.geometry.transformations import compute_camera_params
ValueError: attempted relative import beyond top-level package

WARNING: autodoc: failed to import class 'NeuralMeshRenderer' from module 'graphics'; the following exception was raised:
Traceback (most recent call last):
  File "/home/smosesli/anaconda3/envs/kaolin/lib/python3.6/site-packages/Sphinx-2.2.0-py3.6.egg/sphinx/ext/autodoc/importer.py", line 32, in import_module
    return importlib.import_module(modname)
  File "/home/smosesli/anaconda3/envs/kaolin/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/smosesli/externals/kaolin/kaolin/graphics/__init__.py", line 8, in <module>
    from .DIBRenderer import DIBRenderer
  File "/home/smosesli/externals/kaolin/kaolin/graphics/DIBRenderer.py", line 38, in <module>
    from .dib_renderer.renderer import Renderer as DIBRenderer
  File "/home/smosesli/externals/kaolin/kaolin/graphics/dib_renderer/renderer/__init__.py", line 1, in <module>
    from .base import *
  File "/home/smosesli/externals/kaolin/kaolin/graphics/dib_renderer/renderer/base.py", line 24, in <module>
    from ....mathutils.geometry.transformations import compute_camera_params
ValueError: attempted relative import beyond top-level package

WARNING: autodoc: failed to import class 'SoftRenderer' from module 'graphics'; the following exception was raised:
Traceback (most recent call last):
  File "/home/smosesli/anaconda3/envs/kaolin/lib/python3.6/site-packages/Sphinx-2.2.0-py3.6.egg/sphinx/ext/autodoc/importer.py", line 32, in import_module
    return importlib.import_module(modname)
  File "/home/smosesli/anaconda3/envs/kaolin/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/smosesli/externals/kaolin/kaolin/graphics/__init__.py", line 8, in <module>
    from .DIBRenderer import DIBRenderer
  File "/home/smosesli/externals/kaolin/kaolin/graphics/DIBRenderer.py", line 38, in <module>
    from .dib_renderer.renderer import Renderer as DIBRenderer
  File "/home/smosesli/externals/kaolin/kaolin/graphics/dib_renderer/renderer/__init__.py", line 1, in <module>
    from .base import *
  File "/home/smosesli/externals/kaolin/kaolin/graphics/dib_renderer/renderer/base.py", line 24, in <module>
    from ....mathutils.geometry.transformations import compute_camera_params
ValueError: attempted relative import beyond top-level package

WARNING: autodoc: failed to import class 'DIBRenderer' from module 'graphics'; the following exception was raised:
Traceback (most recent call last):
  File "/home/smosesli/anaconda3/envs/kaolin/lib/python3.6/site-packages/Sphinx-2.2.0-py3.6.egg/sphinx/ext/autodoc/importer.py", line 32, in import_module
    return importlib.import_module(modname)
  File "/home/smosesli/anaconda3/envs/kaolin/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/smosesli/externals/kaolin/kaolin/graphics/__init__.py", line 8, in <module>
    from .DIBRenderer import DIBRenderer
  File "/home/smosesli/externals/kaolin/kaolin/graphics/DIBRenderer.py", line 38, in <module>
    from .dib_renderer.renderer import Renderer as DIBRenderer
  File "/home/smosesli/externals/kaolin/kaolin/graphics/dib_renderer/renderer/__init__.py", line 1, in <module>
    from .base import *
  File "/home/smosesli/externals/kaolin/kaolin/graphics/dib_renderer/renderer/base.py", line 24, in <module>
    from ....mathutils.geometry.transformations import compute_camera_params
ValueError: attempted relative import beyond top-level package

WARNING: autodoc: failed to import function 'Transformations.get_eye_from_spherical_coords' from module 'graphics'; the following exception was raised:
Traceback (most recent call last):
  File "/home/smosesli/anaconda3/envs/kaolin/lib/python3.6/site-packages/Sphinx-2.2.0-py3.6.egg/sphinx/ext/autodoc/importer.py", line 32, in import_module
    return importlib.import_module(modname)
  File "/home/smosesli/anaconda3/envs/kaolin/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/smosesli/externals/kaolin/kaolin/graphics/__init__.py", line 8, in <module>
    from .DIBRenderer import DIBRenderer
  File "/home/smosesli/externals/kaolin/kaolin/graphics/DIBRenderer.py", line 38, in <module>
    from .dib_renderer.renderer import Renderer as DIBRenderer
  File "/home/smosesli/externals/kaolin/kaolin/graphics/dib_renderer/renderer/__init__.py", line 1, in <module>
    from .base import *
  File "/home/smosesli/externals/kaolin/kaolin/graphics/dib_renderer/renderer/base.py", line 24, in <module>
    from ....mathutils.geometry.transformations import compute_camera_params
ValueError: attempted relative import beyond top-level package

Exception occurred:
  File "/home/smosesli/anaconda3/envs/kaolin/lib/python3.6/site-packages/Sphinx-2.2.0-py3.6.egg/sphinx/util/nodes.py", line 151, in apply_source_workaround
    for classifier in reversed(node.parent.traverse(nodes.classifier)):
TypeError: '_traversal_list' object is not reversible
The full traceback has been saved in /tmp/sphinx-err-pdi7sqk9.log, if you want to report the issue to the developers.
Please also report this if it was a user error, so that a better error message can be provided next time.
A bug report can be filed in the tracker at <https://github.com/sphinx-doc/sphinx/issues>. Thanks!
`

I'll appreciate if you could help me understand the reason for the error.
Thank you!

**Comment by HassanAbbas92** [comment]
Prior to running the tests, please run the command source `setenv.sh`, which will point Python to the necessary libraries.

**Comment by anaru** [comment]
I have the same problem. I tried running `source setenv.sh` as suggested, and it doesn't seem to fix it

**Comment by shumash** [comment]
Hi, thank you for using Kaolin! The library went through a major rewrite with the version [0.9.0](https://github.com/NVIDIAGameWorks/kaolin/releases/tag/v0.9.0), and this issue is no longer current.

Please refer to our latest documentation:
[https://kaolin.readthedocs.io/en/latest/](https://kaolin.readthedocs.io/en/latest/)
