### ISSUE TITLE
Kaolin import failed: ImportError: DLL load failed

### ISSUE THREAD

**Issue by nguyenmichau** [NVIDIAGameWorks/kaolin#140]
I've managed to install kaolin with Windows 10 , CUDA 10.0, Python 3.6

However, when i tried to import it in python, this error occurs:

```
>>> import kaolin as kal
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\hong\kaolin-master\kaolin\__init__.py", line 17, in <module>
    from kaolin import conversions
  File "C:\Users\hong\kaolin-master\kaolin\conversions\__init__.py", line 1, in <module>
    from kaolin.conversions.meshconversions import *
  File "C:\Users\hong\kaolin-master\kaolin\conversions\meshconversions.py", line 22, in <module>
    from kaolin.metrics.point import directed_distance as directed_distance
  File "C:\Users\hong\kaolin-master\kaolin\metrics\__init__.py", line 3, in <module>
    from .mesh import *
  File "C:\Users\hong\kaolin-master\kaolin\metrics\mesh.py", line 40, in <module>
    from kaolin.rep import Mesh
  File "C:\Users\hong\kaolin-master\kaolin\rep\__init__.py", line 1, in <module>
    from .Mesh import *
  File "C:\Users\hong\kaolin-master\kaolin\rep\Mesh.py", line 27, in <module>
    import kaolin.cuda.load_textures as load_textures_cuda
ImportError: DLL load failed: Le module spécifié est introuvable.
```
I have tried to add all the CUDA directories in PATH in my environment variables.

![image](https://user-images.githubusercontent.com/16257231/73356972-ce7ec500-429b-11ea-8e5a-9f9e1925cfc0.png)

However the same errors still occur. What should I do?

**Comment by dhirajsuvarna** [comment]
Which visual studio version did you use to build kaolin on window?

**Comment by nguyenmichau** [comment]
I used VS 2017 with the C++ development package installed

**Comment by 1000ping** [comment]
any solution for this I am stuck on this same problem

**Comment by shumash** [comment]
Hi, thank you for using Kaolin! The library went through a major rewrite with the version [0.9.0](https://github.com/NVIDIAGameWorks/kaolin/releases/tag/v0.9.0), and this issue is no longer current.

Please refer to our latest documentation:
[https://kaolin.readthedocs.io/en/latest/](https://kaolin.readthedocs.io/en/latest/)
