### ISSUE TITLE
import error

### ISSUE THREAD

**Issue by shuuchen** [NVIDIAGameWorks/kaolin#154]
Hi, 
I am struggling with it these days. I am using cuda10.1, python 3.6, pytorch 1.4.
I installed it following README. But I cannot import it.

Python 3.6.9 |Anaconda, Inc.| (default, Jul 30 2019, 19:07:31)
[GCC 7.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import kaolin
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/ec2-user/github/kaolin/kaolin/__init__.py", line 17, in <module>
    from kaolin import conversions
  File "/home/ec2-user/github/kaolin/kaolin/conversions/__init__.py", line 1, in <module>
    from kaolin.conversions.meshconversions import *
  File "/home/ec2-user/github/kaolin/kaolin/conversions/meshconversions.py", line 20, in <module>
    from kaolin.metrics.point import directed_distance as directed_distance
  File "/home/ec2-user/github/kaolin/kaolin/metrics/__init__.py", line 2, in <module>
    from .point import *
  File "/home/ec2-user/github/kaolin/kaolin/metrics/point.py", line 17, in <module>
    import kaolin.cuda.sided_distance as sd
ImportError: /home/ec2-user/github/kaolin/kaolin/cuda/sided_distance.cpython-36m-x86_64-linux-gnu.so: undefined symbol: _ZN6caffe26detail37_typeMetaDataInstance_preallocated_32E
>>>

**Comment by cosw0t** [comment]
Did you by any chance upgrade pytorch to 1.4 *after* installing kaolin? The core modules of kaolin compiled with old torch headers may be the cause of the link error.

Try to remove kaolin and reinstall it again with the new version of pytorch.

**Comment by krrish94** [comment]
Closing, inactivity.
