### ISSUE TITLE
In trianglemesh_to_voxelgrid IndexError: too many indices for tensor of dimension 1

### ISSUE THREAD

**Issue by ThibaultGROUEIX** [NVIDIAGameWorks/kaolin#168]
Hi,
It looks like there might be an error in shapenet dataloader. My guess is that it is an unhandled exception from corrupted data in ShapeNetv1.

with ```python train.py --categories plane bench cabinet car chair monitor lamp speaker rifle sofa table phone watercraft```
```
# Setup Dataset
points_set = shapenet.ShapeNet_Points(root=args.shapenet_root, cache_dir=args.cache_dir, categories=args.categories,
                                      train=True, split=.7, num_points=3000)
images_set = shapenet.ShapeNet_Images(root=args.shapenet_images_root, categories=args.categories,
                                      train=True, split=.7, views=23, transform=preprocess)
train_set = shapenet.ShapeNet_Combination([points_set, images_set])
dataloader_train = DataLoader(train_set, batch_size=args.batch_size, shuffle=True,
                              num_workers=8)
```
The full batcktrace :

```
converting to voxels:  62%|█████████████████████████████████████████████████████████████████████████████▌                                                | 18870/30644 [00:02<00:01, 7035.38it/s]
Traceback (most recent call last):
  File "train.py", line 78, in <module>
    train=True, split=.7, num_points=3000)
  File "/home/thibault/anaconda3/envs/python3/lib/python3.6/site-packages/kaolin-0.1.0-py3.6-linux-x86_64.egg/kaolin/datasets/shapenet.py", line 561, in __init__
  File "/home/thibault/anaconda3/envs/python3/lib/python3.6/site-packages/kaolin-0.1.0-py3.6-linux-x86_64.egg/kaolin/datasets/shapenet.py", line 443, in __init__
  File "/home/thibault/anaconda3/envs/python3/lib/python3.6/site-packages/kaolin-0.1.0-py3.6-linux-x86_64.egg/kaolin/datasets/shapenet.py", line 368, in __init__
  File "/home/thibault/anaconda3/envs/python3/lib/python3.6/site-packages/kaolin-0.1.0-py3.6-linux-x86_64.egg/kaolin/transforms/transforms.py", line 99, in __call__
  File "/home/thibault/anaconda3/envs/python3/lib/python3.6/site-packages/kaolin-0.1.0-py3.6-linux-x86_64.egg/kaolin/transforms/transforms.py", line 55, in __call__
  File "/home/thibault/anaconda3/envs/python3/lib/python3.6/site-packages/kaolin-0.1.0-py3.6-linux-x86_64.egg/kaolin/transforms/transforms.py", line 707, in __call__
  File "/home/thibault/anaconda3/envs/python3/lib/python3.6/site-packages/kaolin-0.1.0-py3.6-linux-x86_64.egg/kaolin/conversions/meshconversions.py", line 94, in trianglemesh_to_voxelgrid
IndexError: too many indices for tensor of dimension 1
```

**Comment by krrish94** [comment]
Does this resolve your issue?
https://github.com/NVIDIAGameWorks/kaolin/pull/159

**Comment by ZhenghaoL** [comment]
Hello, i meet the same issue as you. Have you solve it now?

**Comment by Caenorst** [comment]
Hi, thank you for using Kaolin! The library went through a major rewrite with the version 0.9.0, and only the core library components we can thoroughly test and maintain are now part of this repository. Please refer to our latest documentation.

Closing the bug as it is no longer relevant to this repo.
