### ISSUE TITLE
RuntimeError: Error compiling objects for extension during installation of kaolin

### ISSUE THREAD

**Issue by yuyingyeh** [NVIDIAGameWorks/kaolin#204]
Hi, I followed the steps provided in README. I create a virtual environment and installed latest version PyTorch. When I execute `python setup.py build_ext --inplace` or `python setup.py install`, I encountered the following errors. I have tried both python 3.6 and python 3.7. The results are the same. My cuda version is 10.2, PyTorch is 1.5, NumPy is 1.18, ninja version is 1.10. The OS is Ubuntu 18.04. Thanks for your help!

[2/2] /usr/local/cuda/bin/nvcc -I/home/yyyeh/anaconda3/envs/kaolin/lib/python3.7/site-packages/torch/include -I/home/yyyeh/anaconda3/envs/kaolin/lib/python3.7/site-packages/torch/include/torch/csrc/api/include -I/home/yyyeh/anaconda3/envs/kaolin/lib/python3.7/site-packages/torch/include/TH -I/home/yyyeh/anaconda3/envs/kaolin/lib/python3.7/site-packages/torch/include/THC -I/usr/local/cuda/include -I/home/yyyeh/anaconda3/envs/kaolin/lib/python3.7/site-packages/numpy/core/include -I/home/yyyeh/anaconda3/envs/kaolin/include/python3.7m -c -c /home/yyyeh/library/kaolin/kaolin/cuda/load_textures_cuda_kernel.cu -o /home/yyyeh/library/kaolin/build/temp.linux-x86_64-3.7/kaolin/cuda/load_textures_cuda_kernel.o -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr --compiler-options '-fPIC' -Wno-deprecated-declarations -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=load_textures -D_GLIBCXX_USE_CXX11_ABI=0 -gencode=arch=compute_75,code=sm_75 -std=c++14
ninja: build stopped: subcommand failed.
Traceback (most recent call last):
  File "/home/yyyeh/anaconda3/envs/kaolin/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 1400, in _run_ninja_build
    check=True)
  File "/home/yyyeh/anaconda3/envs/kaolin/lib/python3.7/subprocess.py", line 512, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['ninja', '-v']' returned non-zero exit status 1.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "setup.py", line 230, in <module>
    cmdclass={'build_ext': KaolinBuildExtension}
  File "/home/yyyeh/anaconda3/envs/kaolin/lib/python3.7/site-packages/setuptools/__init__.py", line 144, in setup
    return distutils.core.setup(**attrs)
  File "/home/yyyeh/anaconda3/envs/kaolin/lib/python3.7/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/home/yyyeh/anaconda3/envs/kaolin/lib/python3.7/distutils/dist.py", line 966, in run_commands
    self.run_command(cmd)
  File "/home/yyyeh/anaconda3/envs/kaolin/lib/python3.7/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/home/yyyeh/anaconda3/envs/kaolin/lib/python3.7/site-packages/setuptools/command/build_ext.py", line 87, in run
    _build_ext.run(self)
  File "/home/yyyeh/anaconda3/envs/kaolin/lib/python3.7/distutils/command/build_ext.py", line 340, in run
    self.build_extensions()
  File "setup.py", line 89, in build_extensions
    super().build_extensions()
  File "/home/yyyeh/anaconda3/envs/kaolin/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 580, in build_extensions
    build_ext.build_extensions(self)
  File "/home/yyyeh/anaconda3/envs/kaolin/lib/python3.7/distutils/command/build_ext.py", line 449, in build_extensions
    self._build_extensions_serial()
  File "/home/yyyeh/anaconda3/envs/kaolin/lib/python3.7/distutils/command/build_ext.py", line 474, in _build_extensions_serial
    self.build_extension(ext)
  File "/home/yyyeh/anaconda3/envs/kaolin/lib/python3.7/site-packages/setuptools/command/build_ext.py", line 208, in build_extension
    _build_ext.build_extension(self, ext)
  File "/home/yyyeh/anaconda3/envs/kaolin/lib/python3.7/distutils/command/build_ext.py", line 534, in build_extension
    depends=ext.depends)
  File "/home/yyyeh/anaconda3/envs/kaolin/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 423, in unix_wrap_ninja_compile
    with_cuda=with_cuda)
  File "/home/yyyeh/anaconda3/envs/kaolin/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 1140, in _write_ninja_file_and_compile_objects
    error_prefix='Error compiling objects for extension')
  File "/home/yyyeh/anaconda3/envs/kaolin/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 1413, in _run_ninja_build
    raise RuntimeError(message)
RuntimeError: Error compiling objects for extension

**Comment by krrish94** [comment]
@yuyingyeh Does it work with pytorch version `1.4`? We haven't tested builds with version `1.5` yet.

**Comment by yuyingyeh** [comment]
Since there is no official Conda installation for PyTorch 1.4, I rather install PyTorch 1.2. And now I can install kaolin successfully. However, when I tried to import kaolin, I met another error.

(kaolin) yyyeh@ubuntu:~/library$ python
Python 3.6.10 | packaged by conda-forge | (default, Apr  6 2020, 14:52:36) 
[GCC 7.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import kaolin as kal
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/yyyeh/anaconda3/envs/kaolin/lib/python3.6/site-packages/kaolin-0.1.0-py3.6-linux-x86_64.egg/kaolin/__init__.py", line 17, in <module>
  File "/home/yyyeh/anaconda3/envs/kaolin/lib/python3.6/site-packages/kaolin-0.1.0-py3.6-linux-x86_64.egg/kaolin/conversions/__init__.py", line 1, in <module>
  File "/home/yyyeh/anaconda3/envs/kaolin/lib/python3.6/site-packages/kaolin-0.1.0-py3.6-linux-x86_64.egg/kaolin/conversions/meshconversions.py", line 20, in <module>
  File "/home/yyyeh/anaconda3/envs/kaolin/lib/python3.6/site-packages/kaolin-0.1.0-py3.6-linux-x86_64.egg/kaolin/metrics/__init__.py", line 2, in <module>
  File "/home/yyyeh/anaconda3/envs/kaolin/lib/python3.6/site-packages/kaolin-0.1.0-py3.6-linux-x86_64.egg/kaolin/metrics/point.py", line 16, in <module>
  File "/home/yyyeh/anaconda3/envs/kaolin/lib/python3.6/site-packages/kaolin-0.1.0-py3.6-linux-x86_64.egg/kaolin/nnsearch.py", line 7, in <module>
  File "/home/yyyeh/anaconda3/envs/kaolin/lib/python3.6/site-packages/kaolin-0.1.0-py3.6-linux-x86_64.egg/kaolin/nnsearch.py", line 6, in __bootstrap__
  File "/home/yyyeh/anaconda3/envs/kaolin/lib/python3.6/imp.py", line 343, in load_dynamic
    return _load(spec)
ImportError: libtorch_cpu.so: cannot open shared object file: No such file or directory
>>> 

Thanks for your help!

**Comment by krrish94** [comment]
Could you check if pytorch has been compiled using the GPU?
`torch.cuda.is_available()`

**Comment by yuyingyeh** [comment]
Yes, it returns `True`.

I have also tried PyTorch 1.4 with cudatoolkit 10.1, and it returns the same error message.

**Comment by krrish94** [comment]
We have a `Dockerfile` in case of the install errors. This looks weird indeed; I'll see if I can repro.

**Comment by shapovalov** [comment]
I had similar problems. After downgrading Pytorch, it was not able to find the shared library. I then installed from scratch with Pytorch 1.4 in a new environment, and it worked. Hope it helps.

**Comment by krrish94** [comment]
@yuyingyeh This might've been due to a recent PR that broke compatibility. Could you try now? Also, there's a `Dockerfile` (https://github.com/NVIDIAGameWorks/kaolin/blob/master/Dockerfile) to repro.

**Comment by hiyyg** [comment]
When will kaolin support pytorch 1.5?

**Comment by eVen-gits** [comment]
Is there any estimated timeline for pytorch 1.5 + cuda 10.2 support?

**Comment by yuyingyeh** [comment]
@krrish94 I can build the docker image from the Dockerfile. However, I encountered another issue #268.

**Comment by hiyyg** [comment]
PyTorch 1.6 has been released. When will kaolin support PyTorch 1.5 and 1.6?

**Comment by hiyyg** [comment]
@eVen-gits I can successfully build kaolin with pytorch 1.6 and cuda 10.1.

**Comment by MBrandt-NASA** [comment]
It would be great to see Kaolin updated to more recent versions of both Python and Pytorch... it's starting to fall behind in both areas.

I'm looking at using Kaolin on NASA projects, so I'd love to see it continue to be updated, please.  :smiley:

**Comment by ToFirstday** [comment]
> Hi, I followed the steps provided in README. I create a virtual environment and installed latest version PyTorch. When I execute `python setup.py build_ext --inplace` or `python setup.py install`, I encountered the following errors. I have tried both python 3.6 and python 3.7. The results are the same. My cuda version is 10.2, PyTorch is 1.5, NumPy is 1.18, ninja version is 1.10. The OS is Ubuntu 18.04. Thanks for your help!
> 
> [2/2] /usr/local/cuda/bin/nvcc -I/home/yyyeh/anaconda3/envs/kaolin/lib/python3.7/site-packages/torch/include -I/home/yyyeh/anaconda3/envs/kaolin/lib/python3.7/site-packages/torch/include/torch/csrc/api/include -I/home/yyyeh/anaconda3/envs/kaolin/lib/python3.7/site-packages/torch/include/TH -I/home/yyyeh/anaconda3/envs/kaolin/lib/python3.7/site-packages/torch/include/THC -I/usr/local/cuda/include -I/home/yyyeh/anaconda3/envs/kaolin/lib/python3.7/site-packages/numpy/core/include -I/home/yyyeh/anaconda3/envs/kaolin/include/python3.7m -c -c /home/yyyeh/library/kaolin/kaolin/cuda/load_textures_cuda_kernel.cu -o /home/yyyeh/library/kaolin/build/temp.linux-x86_64-3.7/kaolin/cuda/load_textures_cuda_kernel.o -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr --compiler-options '-fPIC' -Wno-deprecated-declarations -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=load_textures -D_GLIBCXX_USE_CXX11_ABI=0 -gencode=arch=compute_75,code=sm_75 -std=c++14 ninja: build stopped: subcommand failed. Traceback (most recent call last): File "/home/yyyeh/anaconda3/envs/kaolin/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 1400, in _run_ninja_build check=True) File "/home/yyyeh/anaconda3/envs/kaolin/lib/python3.7/subprocess.py", line 512, in run output=stdout, stderr=stderr) subprocess.CalledProcessError: Command '['ninja', '-v']' returned non-zero exit status 1.
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last): File "setup.py", line 230, in cmdclass={'build_ext': KaolinBuildExtension} File "/home/yyyeh/anaconda3/envs/kaolin/lib/python3.7/site-packages/setuptools/**init**.py", line 144, in setup return distutils.core.setup(**attrs) File "/home/yyyeh/anaconda3/envs/kaolin/lib/python3.7/distutils/core.py", line 148, in setup dist.run_commands() File "/home/yyyeh/anaconda3/envs/kaolin/lib/python3.7/distutils/dist.py", line 966, in run_commands self.run_command(cmd) File "/home/yyyeh/anaconda3/envs/kaolin/lib/python3.7/distutils/dist.py", line 985, in run_command cmd_obj.run() File "/home/yyyeh/anaconda3/envs/kaolin/lib/python3.7/site-packages/setuptools/command/build_ext.py", line 87, in run _build_ext.run(self) File "/home/yyyeh/anaconda3/envs/kaolin/lib/python3.7/distutils/command/build_ext.py", line 340, in run self.build_extensions() File "setup.py", line 89, in build_extensions super().build_extensions() File "/home/yyyeh/anaconda3/envs/kaolin/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 580, in build_extensions build_ext.build_extensions(self) File "/home/yyyeh/anaconda3/envs/kaolin/lib/python3.7/distutils/command/build_ext.py", line 449, in build_extensions self._build_extensions_serial() File "/home/yyyeh/anaconda3/envs/kaolin/lib/python3.7/distutils/command/build_ext.py", line 474, in _build_extensions_serial self.build_extension(ext) File "/home/yyyeh/anaconda3/envs/kaolin/lib/python3.7/site-packages/setuptools/command/build_ext.py", line 208, in build_extension _build_ext.build_extension(self, ext) File "/home/yyyeh/anaconda3/envs/kaolin/lib/python3.7/distutils/command/build_ext.py", line 534, in build_extension depends=ext.depends) File "/home/yyyeh/anaconda3/envs/kaolin/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 423, in unix_wrap_ninja_compile with_cuda=with_cuda) File "/home/yyyeh/anaconda3/envs/kaolin/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 1140, in _write_ninja_file_and_compile_objects error_prefix='Error compiling objects for extension') File "/home/yyyeh/anaconda3/envs/kaolin/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 1413, in _run_ninja_build raise RuntimeError(message) RuntimeError: Error compiling objects for extension

Hello, I just  encountered the same installing errors as this. And cuda version is 11.1, Pytorch is 1.9.0, NumPy is 1.21.5. Could you tell me how to solve this issuev ?? Thanks very much!
![image](https://user-images.githubusercontent.com/59352671/155691078-c4c2aa4d-51ab-4de2-b933-dd6fe3cfb31d.png)

**Comment by ToFirstday** [comment]
> @yuyingyeh Does it work with pytorch version `1.4`? We haven't tested builds with version `1.5` yet.
Hello, I just encountered the same installing errors as this. And cuda version is 11.1, Pytorch is 1.9.0, NumPy is 1.21.5. Could you tell me how to solve this issuev ?? Thanks very much!
![image](https://user-images.githubusercontent.com/59352671/155713231-989528c3-9c29-443f-b41f-89308a927689.png)

**Comment by ToFirstday** [comment]
> @yuyingyeh Does it work with pytorch version `1.4`? We haven't tested builds with version `1.5` yet.

Hello, I just encountered the same installing errors as this. And cuda version is 11.1, Pytorch is 1.9.0, NumPy is 1.21.5. Could you tell me how to solve this issuev ?? Thanks very much!
![image](https://user-images.githubusercontent.com/59352671/155713423-e5a638ef-8063-4588-b31e-22cb37d62ae0.png)

**Comment by Caenorst** [comment]
Closing for inactivity, most build issues should be resolved now
