### ISSUE TITLE
error importing because of nuscenes dataset? 

### ISSUE THREAD

**Issue by stephansturges** [NVIDIAGameWorks/kaolin#268]
Hi there,

Does anyone else have this problem? 

```
Warning: unable to import datasets/nusc:
   libgthread-2.0.so.0: cannot open shared object file: No such file or directory
Traceback (most recent call last):
  File "/kaolin/kaolin/datasets/__init__.py", line 11, in <module>
    from .nusc import NuscDetection
  File "/kaolin/kaolin/datasets/nusc.py", line 21, in <module>
    from nuscenes.utils.geometry_utils import transform_matrix
  File "/opt/conda/envs/kaolin/lib/python3.6/site-packages/nuscenes/__init__.py", line 1, in <module>

```

Env: Ubuntu 18.04 on AWS NC6 with vanilla Nvidia-docker-cuda:10.2, python 3.6

**Comment by yuyingyeh** [comment]
I use the `Dockerfile` (https://github.com/NVIDIAGameWorks/kaolin/blob/master/Dockerfile) to run. I think I face the similar problem after `import kaolin`.

```
Warning: unable to import datasets/nusc:
   libgthread-2.0.so.0: cannot open shared object file: No such file or directory
Traceback (most recent call last):
  File "/opt/conda/lib/python3.6/site-packages/kaolin-0.1.0-py3.6-linux-x86_64.egg/kaolin/datasets/__init__.py", line 11, in <module>
    from .nusc import NuscDetection
  File "/opt/conda/lib/python3.6/site-packages/kaolin-0.1.0-py3.6-linux-x86_64.egg/kaolin/datasets/nusc.py", line 21, in <module>
    from nuscenes.utils.geometry_utils import transform_matrix
  File "/opt/conda/lib/python3.6/site-packages/nuscenes/__init__.py", line 1, in <module>
    from .nuscenes import NuScenes, NuScenesExplorer
  File "/opt/conda/lib/python3.6/site-packages/nuscenes/nuscenes.py", line 12, in <module>
    import cv2
  File "/opt/conda/lib/python3.6/site-packages/cv2/__init__.py", line 5, in <module>
    from .cv2 import *
ImportError: libgthread-2.0.so.0: cannot open shared object file: No such file or directory
Warning: unable to import datasets/nusc:
   None
```

**Comment by Caenorst** [comment]
This is just a warning, it won't interrupt the script

**Comment by jacobaustin123** [comment]
Running "pip install nuscenes-devkit" works. It looks like nuscenes was removed from PYPI.

**Comment by Caenorst** [comment]
Closing for inactivity
