### ISSUE TITLE
Import kaolin error

### ISSUE THREAD

**Issue by attashe** [NVIDIAGameWorks/kaolin#273]
After install last version from repo I have this error:

```
Python 3.6.9 (default, Nov  7 2019, 10:44:02)
[GCC 8.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import kaolin
Warning: unable to import datasets/nusc:
   No module named 'nuscenes'
Traceback (most recent call last):
  File "<path>/kaolin/kaolin/datasets/__init__.py", line 11, in <module>
    from .nusc import NuscDetection
  File "<path>/kaolin/kaolin/datasets/nusc.py", line 21, in <module>
    from nuscenes.utils.geometry_utils import transform_matrix
ModuleNotFoundError: No module named 'nuscenes'
Warning: unable to import datasets/nusc:
   None
```

**Comment by attashe** [comment]
I've commented this:
```
File "<path>/kaolin/kaolin/datasets/__init__.py", line 11, in <module>
    from .nusc import NuscDetection
```
before fix

**Comment by ocean1100** [comment]
Maybe you should follow the installation instruction and install some packages:
`
pip install --no-dependencies nuscenes-devkit opencv-python-headless scikit-learn joblib pyquaternion cachetools
`

**Comment by oafolabi** [comment]
@ocean1100 thanks for the observation, ... although that instruction is only placed in the windows section of the documentation (it works for linux though). Maybe the documentation should be updated.

**Comment by Caenorst** [comment]
Closing for inactivity
