### ISSUE TITLE
ImportError: cannot import name 'nnsearch' from 'kaolin.nnsearch' 

### ISSUE THREAD

**Issue by alexzhou907** [NVIDIAGameWorks/kaolin#296]
Here is the error when I import ModelNet or ShapeNet from kaolin.datasets outside kaolin root directory. However, when I am inside kaolin root dir, it seems to import okay. I don't know what could have gone wrong. I am using python 3.7, pytorch 1.4.0, torchvision 0.5.0.

I have tried previous solutions by changing outside kaolin root dir. It does not work. 

`
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/vis/u/alex/anaconda3/envs/test/lib/python3.7/site-packages/kaolin-0.1.0-py3.7-linux-x86_64.egg/kaolin/__init__.py", line 17, in <module>
  File "/vis/u/alex/anaconda3/envs/test/lib/python3.7/site-packages/kaolin-0.1.0-py3.7-linux-x86_64.egg/kaolin/conversions/__init__.py", line 1, in <module>
    # -*- coding: utf-8 -*-
  File "/vis/u/alex/anaconda3/envs/test/lib/python3.7/site-packages/kaolin-0.1.0-py3.7-linux-x86_64.egg/kaolin/conversions/meshconversions.py", line 20, in <module>
  File "/vis/u/alex/anaconda3/envs/test/lib/python3.7/site-packages/kaolin-0.1.0-py3.7-linux-x86_64.egg/kaolin/metrics/__init__.py", line 2, in <module>
    """This directory is meant for IPython extensions."""
  File "/vis/u/alex/anaconda3/envs/test/lib/python3.7/site-packages/kaolin-0.1.0-py3.7-linux-x86_64.egg/kaolin/metrics/point.py", line 16, in <module>
ImportError: cannot import name 'nnsearch' from 'kaolin.nnsearch' (/home/alex/.cache/Python-Eggs/kaolin-0.1.0-py3.7-linux-x86_64.egg-tmp/kaolin/nnsearch.cpython-37m-x86_64-linux-gnu.so)
`

I tried reinstall python 3.6, but I get the following error everywhere

`Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/vis/u/alex/anaconda3/envs/test/lib/python3.6/site-packages/kaolin-0.1.0-py3.6-linux-x86_64.egg/kaolin/__init__.py", line 17, in <module>
  File "/vis/u/alex/anaconda3/envs/test/lib/python3.6/site-packages/kaolin-0.1.0-py3.6-linux-x86_64.egg/kaolin/conversions/__init__.py", line 1, in <module>
  File "/vis/u/alex/anaconda3/envs/test/lib/python3.6/site-packages/kaolin-0.1.0-py3.6-linux-x86_64.egg/kaolin/conversions/meshconversions.py", line 20, in <module>
  File "/vis/u/alex/anaconda3/envs/test/lib/python3.6/site-packages/kaolin-0.1.0-py3.6-linux-x86_64.egg/kaolin/metrics/__init__.py", line 2, in <module>
  File "/vis/u/alex/anaconda3/envs/test/lib/python3.6/site-packages/kaolin-0.1.0-py3.6-linux-x86_64.egg/kaolin/metrics/point.py", line 16, in <module>
ImportError: cannot import name 'nnsearch'
`
There was no kaolin installation error so I thought everything succeeded, but import nnsearch doesn't work not even from outside the kaolin root dir.

**Comment by salvadog** [comment]
Exactly the same error here with python 3.6, pytorch 1.4.0, torchvision 0.5.0, `import kaolin` only works in kaolin root dir, but fails anywhere else.

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/username/dependencies/anaconda3/envs/kaolin/lib/python3.6/site-packages/kaolin-0.1.0-py3.6-linux-x86_64.egg/kaolin/__init__.py", line 17, in <module>
  File "/home/username/dependencies/anaconda3/envs/kaolin/lib/python3.6/site-packages/kaolin-0.1.0-py3.6-linux-x86_64.egg/kaolin/conversions/__init__.py", line 1, in <module>
  File "/home/username/dependencies/anaconda3/envs/kaolin/lib/python3.6/site-packages/kaolin-0.1.0-py3.6-linux-x86_64.egg/kaolin/conversions/meshconversions.py", line 20, in <module>
  File "/home/username/dependencies/anaconda3/envs/kaolin/lib/python3.6/site-packages/kaolin-0.1.0-py3.6-linux-x86_64.egg/kaolin/metrics/__init__.py", line 2, in <module>
  File "/home/username/dependencies/anaconda3/envs/kaolin/lib/python3.6/site-packages/kaolin-0.1.0-py3.6-linux-x86_64.egg/kaolin/metrics/point.py", line 16, in <module>
ImportError: cannot import name 'nnsearch'
```

**Comment by salvadog** [comment]
add `export PYTHONPATH=/kaolin root dir:$PYTHONPATH` to `.bashrc` solved my problem.

**Comment by Hzj199** [comment]
> add `export PYTHONPATH=/kaolin root dir:$PYTHONPATH` to `.bashrc` solved my problem.
What does 'kaolin root dir' mean?

**Comment by salvadog** [comment]
> > add `export PYTHONPATH=/kaolin root dir:$PYTHONPATH` to `.bashrc` solved my problem.
> > What does 'kaolin root dir' mean?

the directory contains README.md

**Comment by zhang-heng-shu** [comment]
> Exactly the same error here with python 3.6, pytorch 1.4.0, torchvision 0.5.0, `import kaolin` only works in kaolin root dir, but fails anywhere else.
> 
> ```
> Traceback (most recent call last):
>   File "<stdin>", line 1, in <module>
>   File "/home/username/dependencies/anaconda3/envs/kaolin/lib/python3.6/site-packages/kaolin-0.1.0-py3.6-linux-x86_64.egg/kaolin/__init__.py", line 17, in <module>
>   File "/home/username/dependencies/anaconda3/envs/kaolin/lib/python3.6/site-packages/kaolin-0.1.0-py3.6-linux-x86_64.egg/kaolin/conversions/__init__.py", line 1, in <module>
>   File "/home/username/dependencies/anaconda3/envs/kaolin/lib/python3.6/site-packages/kaolin-0.1.0-py3.6-linux-x86_64.egg/kaolin/conversions/meshconversions.py", line 20, in <module>
>   File "/home/username/dependencies/anaconda3/envs/kaolin/lib/python3.6/site-packages/kaolin-0.1.0-py3.6-linux-x86_64.egg/kaolin/metrics/__init__.py", line 2, in <module>
>   File "/home/username/dependencies/anaconda3/envs/kaolin/lib/python3.6/site-packages/kaolin-0.1.0-py3.6-linux-x86_64.egg/kaolin/metrics/point.py", line 16, in <module>
> ImportError: cannot import name 'nnsearch'
> ```

import kaolin doesn't works in kaolin root dir,
import-im6.q16: not authorized `kal' @ error/constitute.c/WriteImage/1037.
add export PYTHONPATH=/kaolin root dir:$PYTHONPATH to .bashrc also doesn
't  work
any other solution?

**Comment by lorafib** [comment]
> add export PYTHONPATH=/kaolin root dir:$PYTHONPATH to .bashrc solved my problem.

@salvadog 's solution worked for me as well

**Comment by sunshineatnoon** [comment]
> > add `export PYTHONPATH=/kaolin root dir:$PYTHONPATH` to `.bashrc` solved my problem.
> > What does 'kaolin root dir' mean?

This gives me another error: `ModuleNotFoundError: No module named 'kaolin.nnsearch'`

**Comment by shumash** [comment]
Closing old issue, as no longer relevant to the library.
