### ISSUE TITLE
ModuleNotFoundError: No module named 'kaolin.nnsearch'

### ISSUE THREAD

**Issue by amiltonwong** [NVIDIAGameWorks/kaolin#3]
Hi, all,

After successfully building kaolin, I got the import error as follows:

```
(kaolin) root@milton-ThinkCentre-M93p:/data/code10/kaolin# python
Python 3.6.9 |Anaconda, Inc.| (default, Jul 30 2019, 19:07:31) 
[GCC 7.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import kaolin as kal
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/data/code10/kaolin/kaolin/__init__.py", line 17, in <module>
    from kaolin import conversions
  File "/data/code10/kaolin/kaolin/conversions/__init__.py", line 1, in <module>
    from kaolin.conversions.meshconversions import *
  File "/data/code10/kaolin/kaolin/conversions/meshconversions.py", line 22, in <module>
    from kaolin.metrics.point import directed_distance as directed_distance
  File "/data/code10/kaolin/kaolin/metrics/__init__.py", line 2, in <module>
    from .point import *
  File "/data/code10/kaolin/kaolin/metrics/point.py", line 16, in <module>
    from kaolin.nnsearch import nnsearch
ModuleNotFoundError: No module named 'kaolin.nnsearch'

``` 

Any suggestion to fix this issue?

THX!

**Comment by amsoftgroup** [comment]
I have exactly the same problem. CentOS 7, with all the prereqs.

**Comment by hungsing92** [comment]
try: source setenv.sh

**Comment by hubert0527** [comment]
No, you just need to `cd` out of the `.../kaolin/` directory

**Comment by amiltonwong** [comment]
@hubert0527 , thanks a lot. Just jump out of kaolin directory

**Comment by monajalal** [comment]
cd ing to .. of kaolin doesn't work
```

(/scratch3/3d_pose/kaolin_env) [jalal@goku scratch3]$ cd 3d_pose/
(/scratch3/3d_pose/kaolin_env) [jalal@goku 3d_pose]$ ls
total 2608
-rw-r--r--.  1 jalal cs-grad 1361087 Nov 27 21:31 76261N.pdf
-rw-r--r--.  1 jalal cs-grad 1269366 Nov 27 21:32 79620V.pdf
drwxr-xr-x. 13 jalal cs-grad    4096 Dec  1 18:00 humanpose
drwxrwxrwt. 38 root  root      16384 Dec  2 21:37 ..
drwxr-xr-x. 18 jalal animal     4096 Dec  3 11:09 animalpose
drwxr-xr-x. 12 jalal cs-grad    4096 Dec  3 11:27 kaolin
drwxr-xr-x.  6 jalal cs-grad     137 Dec  3 11:38 .
drwxr-xr-x. 21 jalal cs-grad    4096 Dec  3 11:40 kaolin_env
(/scratch3/3d_pose/kaolin_env) [jalal@goku 3d_pose]$ python
Python 3.6.7 | packaged by conda-forge | (default, Nov  6 2019, 16:19:42) 
[GCC 7.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import kaolin
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/scratch3/3d_pose/kaolin_env/lib/python3.6/site-packages/kaolin-0.2.0+75b95ec-py3.6-linux-x86_64.egg/kaolin/__init__.py", line 17, in <module>
  File "/scratch3/3d_pose/kaolin_env/lib/python3.6/site-packages/kaolin-0.2.0+75b95ec-py3.6-linux-x86_64.egg/kaolin/conversions/__init__.py", line 1, in <module>
  File "/scratch3/3d_pose/kaolin_env/lib/python3.6/site-packages/kaolin-0.2.0+75b95ec-py3.6-linux-x86_64.egg/kaolin/conversions/meshconversions.py", line 22, in <module>
  File "/scratch3/3d_pose/kaolin_env/lib/python3.6/site-packages/kaolin-0.2.0+75b95ec-py3.6-linux-x86_64.egg/kaolin/metrics/__init__.py", line 3, in <module>
  File "/scratch3/3d_pose/kaolin_env/lib/python3.6/site-packages/kaolin-0.2.0+75b95ec-py3.6-linux-x86_64.egg/kaolin/metrics/mesh.py", line 40, in <module>
  File "/scratch3/3d_pose/kaolin_env/lib/python3.6/site-packages/kaolin-0.2.0+75b95ec-py3.6-linux-x86_64.egg/kaolin/rep/__init__.py", line 6, in <module>
  File "/scratch3/3d_pose/kaolin_env/lib/python3.6/site-packages/kaolin-0.2.0+75b95ec-py3.6-linux-x86_64.egg/kaolin/rep/SDF.py", line 43, in <module>
  File "/scratch3/3d_pose/kaolin_env/lib/python3.6/site-packages/kaolin-0.2.0+75b95ec-py3.6-linux-x86_64.egg/kaolin/cuda/mesh_intersection.py", line 7, in <module>
  File "/scratch3/3d_pose/kaolin_env/lib/python3.6/site-packages/kaolin-0.2.0+75b95ec-py3.6-linux-x86_64.egg/kaolin/cuda/mesh_intersection.py", line 6, in __bootstrap__
  File "/scratch3/3d_pose/kaolin_env/lib/python3.6/imp.py", line 343, in load_dynamic
    return _load(spec)
ImportError: /lib64/libstdc++.so.6: version `GLIBCXX_3.4.20' not found (required by /home/grad3/jalal/.cache/Python-Eggs/kaolin-0.2.0+75b95ec-py3.6-linux-x86_64.egg-tmp/kaolin/cuda/mesh_intersection.cpython-36m-x86_64-linux-gnu.so)
>>> exit()
(/scratch3/3d_pose/kaolin_env) [jalal@goku 3d_pose]$ ls
total 2608
-rw-r--r--.  1 jalal cs-grad 1361087 Nov 27 21:31 76261N.pdf
-rw-r--r--.  1 jalal cs-grad 1269366 Nov 27 21:32 79620V.pdf
drwxr-xr-x. 13 jalal cs-grad    4096 Dec  1 18:00 humanpose
drwxrwxrwt. 38 root  root      16384 Dec  2 21:37 ..
drwxr-xr-x. 18 jalal animal     4096 Dec  3 11:09 animalpose
drwxr-xr-x. 12 jalal cs-grad    4096 Dec  3 11:27 kaolin
drwxr-xr-x.  6 jalal cs-grad     137 Dec  3 11:38 .
drwxr-xr-x. 21 jalal cs-grad    4096 Dec  3 11:40 kaolin_env
(/scratch3/3d_pose/kaolin_env) [jalal@goku 3d_pose]$ 
```

**Comment by hubert0527** [comment]
@monajalal your error is a different issue (it is `ImportError`). There should be some problems with your C++ version or library linking.
