### ISSUE TITLE
Verify installation  problem

### ISSUE THREAD

**Issue by zyz-notebooks** [NVIDIAGameWorks/kaolin#308]
import kaolin as kal
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/zyz/Project/kaolin/kaolin/__init__.py", line 17, in <module>
    from kaolin import conversions
  File "/home/zyz/Project/kaolin/kaolin/conversions/__init__.py", line 1, in <module>
    from kaolin.conversions.meshconversions import *
  File "/home/zyz/Project/kaolin/kaolin/conversions/meshconversions.py", line 20, in <module>
    from kaolin.metrics.point import directed_distance as directed_distance
  File "/home/zyz/Project/kaolin/kaolin/metrics/__init__.py", line 2, in <module>
    from .point import *
  File "/home/zyz/Project/kaolin/kaolin/metrics/point.py", line 16, in <module>
    from kaolin.nnsearch import nnsearch
ImportError: libtorch_cpu.so: cannot open shared object file: No such file or directory

**Comment by Neural-Net-Ninja** [comment]
@zyz-1998 were you able to solve it? I'm having the same error. ¨ImportError: libtorch_cpu.so: cannot open shared object file: No such file or directory¨

**Comment by kwansik** [comment]
I have same issue with pytorch 1.2 and 1.4. what gives?  (it's kaolin version 0.1, cuda 10.0, cudnn 7.6.5, ryzen 5 cpu, RTX 3080, nvidia driver 455, by the way)

**Comment by shumash** [comment]
Hi, thank you for using Kaolin! The library went through a major rewrite with the version [0.9.0](https://github.com/NVIDIAGameWorks/kaolin/releases/tag/v0.9.0), and this issue is no longer current. Please refer to our latest documentation:
[https://kaolin.readthedocs.io/en/latest/](https://kaolin.readthedocs.io/en/latest/)
