### ISSUE TITLE
Windows installation problem

### ISSUE THREAD

**Issue by kfarivar** [NVIDIAGameWorks/kaolin#320]
I know windows is not supported, but any chance you can help with this single error  ?

I followed the steps in the windows installation section when running `python setup.py build_ext --inplace`

first I resolved the ". is not a command" error on line 70, by changing the backslash to double slash :

```
def build_deps():
    print('Building nv-usd...')
    os.system('.**\\**buildusd.sh')
```

But I still couldn't solve this error:

(kaolin) C:\Users\User\Desktop\Kiarash\kaolin\kaolin>python setup.py build_ext --inplace
WARNING - Kaolin is tested with PyTorch >=1.2.0, <1.5.0 Found version 1.7.0 instead.
WARNING - Kaolin is tested with torchvision >=0.4.0, <0.6.0 Found version 0.8.1 instead.
Building nv-usd...
Traceback (most recent call last):
  File "setup.py", line 240, in <module>
    ext_modules=get_extensions(),
  File "setup.py", line 154, in get_extensions
    'kaolin/cuda/load_textures_cuda_kernel.cu',
  File "setup.py", line 90, in KaolinCUDAExtension
    return CUDAExtension(*args, **kwargs)
  File "C:\Users\User\anaconda3\envs\kaolin\lib\site-packages\torch\utils\cpp_extension.py", line 783, in CUDAExtension
    library_dirs += library_paths(cuda=True)
  File "C:\Users\User\anaconda3\envs\kaolin\lib\site-packages\torch\utils\cpp_extension.py", line 882, in library_paths
    paths.append(_join_cuda_home(lib_dir))
  File "C:\Users\User\anaconda3\envs\kaolin\lib\site-packages\torch\utils\cpp_extension.py", line 1794, in _join_cuda_home
    raise EnvironmentError('CUDA_HOME environment variable is not set. '
OSError: CUDA_HOME environment variable is not set. Please set it to your CUDA install root.

**Comment by kfarivar** [comment]
Is it possible to use the library without installation ? just directly cloning the repo ?

**Comment by kfarivar** [comment]
Ok, I didn't realize that I had to install the CUDA toolkit using this [guide](https://docs.nvidia.com/cuda/cuda-installation-guide-microsoft-windows/index.html).

But now I get the following error:

(kaolin) C:\Users\User\Desktop\Kiarash\kaolin\kaolin>python setup.py build_ext --inplace
WARNING - Kaolin is tested with PyTorch >=1.2.0, <1.5.0 Found version 1.7.0 instead.
WARNING - Kaolin is tested with torchvision >=0.4.0, <0.6.0 Found version 0.8.1 instead.
Building nv-usd...
running build_ext
Traceback (most recent call last):
  File "setup.py", line 242, in <module>
    cmdclass={'build_ext': KaolinBuildExtension}
  File "C:\Users\User\anaconda3\envs\kaolin\lib\site-packages\setuptools\__init__.py", line 153, in setup
    return distutils.core.setup(**attrs)
  File "C:\Users\User\anaconda3\envs\kaolin\lib\distutils\core.py", line 148, in setup
    dist.run_commands()
  File "C:\Users\User\anaconda3\envs\kaolin\lib\distutils\dist.py", line 955, in run_commands
    self.run_command(cmd)
  File "C:\Users\User\anaconda3\envs\kaolin\lib\distutils\dist.py", line 974, in run_command
    cmd_obj.run()
  File "C:\Users\User\anaconda3\envs\kaolin\lib\site-packages\setuptools\command\build_ext.py", line 79, in run
    _build_ext.run(self)
  File "C:\Users\User\anaconda3\envs\kaolin\lib\distutils\command\build_ext.py", line 339, in run
    self.build_extensions()
  File "setup.py", line 105, in build_extensions
    super().build_extensions()
  File "C:\Users\User\anaconda3\envs\kaolin\lib\site-packages\torch\utils\cpp_extension.py", line 348, in build_extensions
    self._check_abi()
  File "C:\Users\User\anaconda3\envs\kaolin\lib\site-packages\torch\utils\cpp_extension.py", line 685, in _check_abi
    raise UserWarning(msg)
UserWarning: It seems that the VC environment is activated but DISTUTILS_USE_SDK is not set.This may lead to multiple activations of the VC env.Please set `DISTUTILS_USE_SDK=1` and try again.

**Comment by kfarivar** [comment]
ok so in this [merge](https://github.com/NVIDIAGameWorks/kaolin/pull/263)
I found this that fixed the issue : 

> I'd recommend also including in the Windows instructions, either immediately before or after the vcvars64.bat command, the following:
> 
> set DISTUTILS_USE_SDK=1
> 
> I've had to do that each time. Yes it's in the output as a suggestion when you try to run "python setup.py" but it would save dealing with the error to explicitly mention that in the Windows instructions.

**Comment by shumash** [comment]
Hi, thank you for using Kaolin! The library went through a major rewrite with the version [0.9.0](https://github.com/NVIDIAGameWorks/kaolin/releases/tag/v0.9.0), and this issue is no longer current.

Please refer to our latest documentation:
[https://kaolin.readthedocs.io/en/latest/](https://kaolin.readthedocs.io/en/latest/)
