### ISSUE TITLE
python setup.py build_ext --inplace failed

### ISSUE THREAD

**Issue by jiaqiAA** [NVIDIAGameWorks/kaolin#343]
Hi,
I tried running `python setup.py build_ext --inplace` but I experienced the following error:

Warning: passing language='c++' to cythonize() is deprecated. Instead, put "# distutils: language=c++" in your .pyx or .pxd file(s)
running build_ext
building 'kaolin.ops.packed_sum_cuda' extension
Emitting ninja build file /home/ubuntu/Downloads/kaolin/build/temp.linux-x86_64-3.7/build.ninja...
Compiling objects...
Allowing ninja to set a default number of workers... (overridable by setting the environment variable MAX_JOBS=N)
[1/1] :/usr/local/cuda-11.1/bin/nvcc -DWITH_CUDA -I/home/ubuntu/anaconda3/envs/kaolin/lib/python3.7/site-packages/torch/include -I/home/ubuntu/anaconda3/envs/kaolin/lib/python3.7/site-packages/torch/include/torch/csrc/api/include -I/home/ubuntu/anaconda3/envs/kaolin/lib/python3.7/site-packages/torch/include/TH -I/home/ubuntu/anaconda3/envs/kaolin/lib/python3.7/site-packages/torch/include/THC -I:/usr/local/cuda-11.1/include -I/home/ubuntu/anaconda3/envs/kaolin/include/python3.7m -c -c /home/ubuntu/Downloads/kaolin/kaolin/csrc/cuda/ops/packed_sum_cuda_kernel.cu -o /home/ubuntu/Downloads/kaolin/build/temp.linux-x86_64-3.7/kaolin/csrc/cuda/ops/packed_sum_cuda_kernel.o -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr --compiler-options ''"'"'-fPIC'"'"'' -O3 -DTORCH_API_INCLUDE_EXTENSION_H '-DPYBIND11_COMPILER_TYPE="_gcc"' '-DPYBIND11_STDLIB="_libstdcpp"' '-DPYBIND11_BUILD_ABI="_cxxabi1011"' -DTORCH_EXTENSION_NAME=packed_sum_cuda -D_GLIBCXX_USE_CXX11_ABI=0 -gencode=arch=compute_86,code=sm_86 -std=c++14
FAILED: /home/ubuntu/Downloads/kaolin/build/temp.linux-x86_64-3.7/kaolin/csrc/cuda/ops/packed_sum_cuda_kernel.o 
:/usr/local/cuda-11.1/bin/nvcc -DWITH_CUDA -I/home/ubuntu/anaconda3/envs/kaolin/lib/python3.7/site-packages/torch/include -I/home/ubuntu/anaconda3/envs/kaolin/lib/python3.7/site-packages/torch/include/torch/csrc/api/include -I/home/ubuntu/anaconda3/envs/kaolin/lib/python3.7/site-packages/torch/include/TH -I/home/ubuntu/anaconda3/envs/kaolin/lib/python3.7/site-packages/torch/include/THC -I:/usr/local/cuda-11.1/include -I/home/ubuntu/anaconda3/envs/kaolin/include/python3.7m -c -c /home/ubuntu/Downloads/kaolin/kaolin/csrc/cuda/ops/packed_sum_cuda_kernel.cu -o /home/ubuntu/Downloads/kaolin/build/temp.linux-x86_64-3.7/kaolin/csrc/cuda/ops/packed_sum_cuda_kernel.o -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr --compiler-options ''"'"'-fPIC'"'"'' -O3 -DTORCH_API_INCLUDE_EXTENSION_H '-DPYBIND11_COMPILER_TYPE="_gcc"' '-DPYBIND11_STDLIB="_libstdcpp"' '-DPYBIND11_BUILD_ABI="_cxxabi1011"' -DTORCH_EXTENSION_NAME=packed_sum_cuda -D_GLIBCXX_USE_CXX11_ABI=0 -gencode=arch=compute_86,code=sm_86 -std=c++14
/bin/sh: 1: :/usr/local/cuda-11.1/bin/nvcc: not found
ninja: build stopped: subcommand failed.
Traceback (most recent call last):
  File "/home/ubuntu/anaconda3/envs/kaolin/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 1539, in _run_ninja_build
    env=env)
  File "/home/ubuntu/anaconda3/envs/kaolin/lib/python3.7/subprocess.py", line 512, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['ninja', '-v']' returned non-zero exit status 1.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "setup.py", line 273, in <module>
    'build_ext': BuildExtension.with_options(no_python_abi_suffix=True)
  File "/home/ubuntu/anaconda3/envs/kaolin/lib/python3.7/site-packages/setuptools/__init__.py", line 153, in setup
    return distutils.core.setup(**attrs)
  File "/home/ubuntu/anaconda3/envs/kaolin/lib/python3.7/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/home/ubuntu/anaconda3/envs/kaolin/lib/python3.7/distutils/dist.py", line 966, in run_commands
    self.run_command(cmd)
  File "/home/ubuntu/anaconda3/envs/kaolin/lib/python3.7/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/home/ubuntu/anaconda3/envs/kaolin/lib/python3.7/site-packages/setuptools/command/build_ext.py", line 79, in run
    _build_ext.run(self)
  File "/home/ubuntu/anaconda3/envs/kaolin/lib/python3.7/site-packages/Cython/Distutils/old_build_ext.py", line 186, in run
    _build_ext.build_ext.run(self)
  File "/home/ubuntu/anaconda3/envs/kaolin/lib/python3.7/distutils/command/build_ext.py", line 340, in run
    self.build_extensions()
  File "/home/ubuntu/anaconda3/envs/kaolin/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 670, in build_extensions
    build_ext.build_extensions(self)
  File "/home/ubuntu/anaconda3/envs/kaolin/lib/python3.7/site-packages/Cython/Distutils/old_build_ext.py", line 195, in build_extensions
    _build_ext.build_ext.build_extensions(self)
  File "/home/ubuntu/anaconda3/envs/kaolin/lib/python3.7/distutils/command/build_ext.py", line 449, in build_extensions
    self._build_extensions_serial()
  File "/home/ubuntu/anaconda3/envs/kaolin/lib/python3.7/distutils/command/build_ext.py", line 474, in _build_extensions_serial
    self.build_extension(ext)
  File "/home/ubuntu/anaconda3/envs/kaolin/lib/python3.7/site-packages/setuptools/command/build_ext.py", line 196, in build_extension
    _build_ext.build_extension(self, ext)
  File "/home/ubuntu/anaconda3/envs/kaolin/lib/python3.7/distutils/command/build_ext.py", line 534, in build_extension
    depends=ext.depends)
  File "/home/ubuntu/anaconda3/envs/kaolin/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 500, in unix_wrap_ninja_compile
    with_cuda=with_cuda)
  File "/home/ubuntu/anaconda3/envs/kaolin/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 1255, in _write_ninja_file_and_compile_objects
    error_prefix='Error compiling objects for extension')
  File "/home/ubuntu/anaconda3/envs/kaolin/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 1555, in _run_ninja_build
    raise RuntimeError(message) from e
RuntimeError: Error compiling objects for extension

I can't find any solutions. Do you know how to fix this issue?

System:
OS: Ubuntu 18.04
Python version: 3.7.6
PyTorch version: 1.7.1
Torchvision version: 0.8.2
CUDA/cuDNN version: 11.1/8.0.4
GPU: RTX3080

**Comment by Caenorst** [comment]
Hi @ljq2020 , `python setup.py build_ext --inplace` is not the recommended installation command anymore, please follow our installation guidelines: https://kaolin.readthedocs.io/en/latest/notes/installation.html
