### ISSUE TITLE
unsupported gpu architecture 'compute_86'. Unable to build for rtx 3090, cuda 11.0

### ISSUE THREAD

**Issue by Shreeyak** [NVIDIAGameWorks/kaolin#351]
I'm getting an error when trying to build for RTX 3090 with CUDA11.0:

```
python setup.py develop          
setup.py:37: UserWarning: Couldn't find cython installed, so this will try to install it. If the installation fails we recommend to first instal it.
  warnings.warn("Couldn't find cython installed, so this will try to install it. "
Warning: passing language='c++' to cythonize() is deprecated. Instead, put "# distutils: language=c++" in your .pyx or .pxd file(s)
running develop
running egg_info
writing kaolin.egg-info/PKG-INFO
writing dependency_links to kaolin.egg-info/dependency_links.txt
writing requirements to kaolin.egg-info/requires.txt
writing top-level names to kaolin.egg-info/top_level.txt
reading manifest file 'kaolin.egg-info/SOURCES.txt'
writing manifest file 'kaolin.egg-info/SOURCES.txt'
running build_ext
building 'kaolin.ops.packed_sum_cuda' extension
Emitting ninja build file /home/shrek/work/ref-repos/kaolin/build/temp.linux-x86_64-3.8/build.ninja...
Compiling objects...
Allowing ninja to set a default number of workers... (overridable by setting the environment variable MAX_JOBS=N)
[1/1] /usr/local/cuda-11.0/bin/nvcc -DWITH_CUDA -I/home/shrek/miniconda3/envs/cleargrasp/lib/python3.8/site-packages/torch/include -I/home/shrek/miniconda3/envs/cleargrasp/lib/python3.8/site-packages/torch/include/torch/csrc/api/include -I/home/shrek/miniconda3/envs/cleargrasp/lib/python3.8/site-packages/torch/include/TH -I/home/shrek/miniconda3/envs/cleargrasp/lib/python3.8/site-packages/torch/include/THC -I/usr/local/cuda-11.0/include -I/home/shrek/miniconda3/envs/cleargrasp/include/python3.8 -c -c /home/shrek/work/ref-repos/kaolin/kaolin/csrc/cuda/ops/packed_sum_cuda_kernel.cu -o /home/shrek/work/ref-repos/kaolin/build/temp.linux-x86_64-3.8/kaolin/csrc/cuda/ops/packed_sum_cuda_kernel.o -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr --compiler-options ''"'"'-fPIC'"'"'' -O3 -DTORCH_API_INCLUDE_EXTENSION_H '-DPYBIND11_COMPILER_TYPE="_gcc"' '-DPYBIND11_STDLIB="_libstdcpp"' '-DPYBIND11_BUILD_ABI="_cxxabi1011"' -DTORCH_EXTENSION_NAME=packed_sum_cuda -D_GLIBCXX_USE_CXX11_ABI=0 -gencode=arch=compute_86,code=sm_86 -std=c++14
FAILED: /home/shrek/work/ref-repos/kaolin/build/temp.linux-x86_64-3.8/kaolin/csrc/cuda/ops/packed_sum_cuda_kernel.o 
/usr/local/cuda-11.0/bin/nvcc -DWITH_CUDA -I/home/shrek/miniconda3/envs/cleargrasp/lib/python3.8/site-packages/torch/include -I/home/shrek/miniconda3/envs/cleargrasp/lib/python3.8/site-packages/torch/include/torch/csrc/api/include -I/home/shrek/miniconda3/envs/cleargrasp/lib/python3.8/site-packages/torch/include/TH -I/home/shrek/miniconda3/envs/cleargrasp/lib/python3.8/site-packages/torch/include/THC -I/usr/local/cuda-11.0/include -I/home/shrek/miniconda3/envs/cleargrasp/include/python3.8 -c -c /home/shrek/work/ref-repos/kaolin/kaolin/csrc/cuda/ops/packed_sum_cuda_kernel.cu -o /home/shrek/work/ref-repos/kaolin/build/temp.linux-x86_64-3.8/kaolin/csrc/cuda/ops/packed_sum_cuda_kernel.o -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr --compiler-options ''"'"'-fPIC'"'"'' -O3 -DTORCH_API_INCLUDE_EXTENSION_H '-DPYBIND11_COMPILER_TYPE="_gcc"' '-DPYBIND11_STDLIB="_libstdcpp"' '-DPYBIND11_BUILD_ABI="_cxxabi1011"' -DTORCH_EXTENSION_NAME=packed_sum_cuda -D_GLIBCXX_USE_CXX11_ABI=0 -gencode=arch=compute_86,code=sm_86 -std=c++14
nvcc fatal   : Unsupported gpu architecture 'compute_86'
ninja: build stopped: subcommand failed.
Traceback (most recent call last):
  File "/home/shrek/miniconda3/envs/cleargrasp/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 1533, in _run_ninja_build
    subprocess.run(
  File "/home/shrek/miniconda3/envs/cleargrasp/lib/python3.8/subprocess.py", line 512, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['ninja', '-v']' returned non-zero exit status 1.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "setup.py", line 256, in <module>
    setup(
  File "/home/shrek/miniconda3/envs/cleargrasp/lib/python3.8/site-packages/setuptools/__init__.py", line 153, in setup
    return distutils.core.setup(**attrs)
  File "/home/shrek/miniconda3/envs/cleargrasp/lib/python3.8/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/home/shrek/miniconda3/envs/cleargrasp/lib/python3.8/distutils/dist.py", line 966, in run_commands
    self.run_command(cmd)
  File "/home/shrek/miniconda3/envs/cleargrasp/lib/python3.8/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/home/shrek/miniconda3/envs/cleargrasp/lib/python3.8/site-packages/setuptools/command/develop.py", line 34, in run
    self.install_for_development()
  File "/home/shrek/miniconda3/envs/cleargrasp/lib/python3.8/site-packages/setuptools/command/develop.py", line 136, in install_for_development
    self.run_command('build_ext')
  File "/home/shrek/miniconda3/envs/cleargrasp/lib/python3.8/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/home/shrek/miniconda3/envs/cleargrasp/lib/python3.8/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/home/shrek/miniconda3/envs/cleargrasp/lib/python3.8/site-packages/setuptools/command/build_ext.py", line 79, in run
    _build_ext.run(self)
  File "/home/shrek/work/ref-repos/kaolin/.eggs/Cython-0.29.20-py3.8-linux-x86_64.egg/Cython/Distutils/old_build_ext.py", line 186, in run
    _build_ext.build_ext.run(self)
  File "/home/shrek/miniconda3/envs/cleargrasp/lib/python3.8/distutils/command/build_ext.py", line 340, in run
    self.build_extensions()
  File "/home/shrek/miniconda3/envs/cleargrasp/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 670, in build_extensions
    build_ext.build_extensions(self)
  File "/home/shrek/work/ref-repos/kaolin/.eggs/Cython-0.29.20-py3.8-linux-x86_64.egg/Cython/Distutils/old_build_ext.py", line 195, in build_extensions
    _build_ext.build_ext.build_extensions(self)
  File "/home/shrek/miniconda3/envs/cleargrasp/lib/python3.8/distutils/command/build_ext.py", line 449, in build_extensions
    self._build_extensions_serial()
  File "/home/shrek/miniconda3/envs/cleargrasp/lib/python3.8/distutils/command/build_ext.py", line 474, in _build_extensions_serial
    self.build_extension(ext)
  File "/home/shrek/miniconda3/envs/cleargrasp/lib/python3.8/site-packages/setuptools/command/build_ext.py", line 196, in build_extension
    _build_ext.build_extension(self, ext)
  File "/home/shrek/miniconda3/envs/cleargrasp/lib/python3.8/distutils/command/build_ext.py", line 528, in build_extension
    objects = self.compiler.compile(sources,
  File "/home/shrek/miniconda3/envs/cleargrasp/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 491, in unix_wrap_ninja_compile
    _write_ninja_file_and_compile_objects(
  File "/home/shrek/miniconda3/envs/cleargrasp/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 1250, in _write_ninja_file_and_compile_objects
    _run_ninja_build(
  File "/home/shrek/miniconda3/envs/cleargrasp/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 1555, in _run_ninja_build
    raise RuntimeError(message) from e
RuntimeError: Error compiling objects for extension
```

**Comment by haohlin** [comment]
Same issue here with 3090 and CUDA 11.2. Have you found a solution?

**Comment by Caenorst** [comment]
Hi!
We tested Kaolin against 3090 RTX, this is most likely a driver or a PATH issue: https://forums.developer.nvidia.com/t/nvcc-fatal-unsupported-gpu-architecture-compute-86/161424/4

**Comment by haohlin** [comment]
Thank you! It turns out that I installed the conda package `cudatoolkit-dev ==10.1` in the designated conda venv, which shadowed global PATH to CUDA 11. 

I reinstalled CUDA 11.3, removed `cudatoolkit-dev`, then installed PyTorch with:
```
pip install torch==1.7.0+cu110 torchvision==0.8.1+cu110 torchaudio===0.7.0 -f https://download.pytorch.org/whl/torch_stable.html
```
Now everything compiles and runs fine.
