### ISSUE TITLE
Segmentation Fault (core dumped) after training PointNet

### ISSUE THREAD

**Issue by seangrate** [NVIDIAGameWorks/kaolin#36]
Any time I try to train PointNet (following the code providing in `kaolin/examples/Classification/`, it trains and validates for all of the specified epochs, but at the very end, a `Segmentation fault (core dumped)` error is raised.

Here is the code for the Python script:
```from pathlib import Path

import torch
from torch.utils.data import DataLoader
import kaolin as kal
from kaolin import ClassificationEngine
from kaolin.datasets import ModelNet10
from kaolin.models.PointNet import PointNetClassifier as PointNet
from kaolin.transforms import NormalizePointCloud


if __name__ == "__main__":
    modelnet_path = Path("/user/data/ModelNet10/")
    engines = {"epochs":10, "print-every":10, "save":True, "savedir":Path.cwd()}
    cats = ['bathtub', 'bed', 'chair', 'desk', 'dresser', 'monitor', 'night_stand', 'sofa', 'table', 'toilet']
    bs = 12

    print(f"kaolin version: {kal.__version__}\n\n")

    norm = NormalizePointCloud()
    train_loader = DataLoader(ModelNet10(modelnet_path, categories=cats,
                                         split='train', rep='pointcloud', transform=norm, device='cuda:0'),
                              batch_size=bs, shuffle=True)
    val_loader = DataLoader(ModelNet10(modelnet_path, categories=cats,
                                       split='test', rep='pointcloud', transform=norm, device='cuda:0'),
                            batch_size=bs)

    engine = ClassificationEngine(PointNet(num_classes=len(cats)), train_loader, val_loader, engineparams=engines, device='cuda:0')
    engine.fit()
```

Here is the output from gdb after I ran `backtrace` after running the script and got a `Segmentation fault (core dumped)` error:
```#0  0x00007fffec93b7d8 in ?? () from /user/miniconda3/envs/kaolin_test/lib/python3.6/site-packages/torch/lib/../../../../libcudart.so.10.1
#1  0x00007fffec941b01 in ?? () from /user/miniconda3/envs/kaolin_test/lib/python3.6/site-packages/torch/lib/../../../../libcudart.so.10.1
#2  0x00007fffec93498e in ?? () from /user/miniconda3/envs/kaolin_test/lib/python3.6/site-packages/torch/lib/../../../../libcudart.so.10.1
#3  0x00007fffec935006 in ?? () from /user/miniconda3/envs/kaolin_test/lib/python3.6/site-packages/torch/lib/../../../../libcudart.so.10.1
#4  0x00007fff66af27d0 in __cudaUnregisterBinaryUtil() ()
   from /user/.cache/Python-Eggs/kaolin-0.2.0+f858c58-py3.6-linux-x86_64.egg-tmp/kaolin/cuda/three_nn.cpython-36m-x86_64-linux-gnu.so
#5  0x00007ffff7808041 in __run_exit_handlers (status=0, listp=0x7ffff7bb0718 <__exit_funcs>, run_list_atexit=run_list_atexit@entry=true, 
    run_dtors=run_dtors@entry=true) at exit.c:108
#6  0x00007ffff780813a in __GI_exit (status=<optimized out>) at exit.c:139
#7  0x00007ffff77e6b9e in __libc_start_main (main=0x5555556377a0 <main>, argc=2, argv=0x7fffffffe148, init=<optimized out>, fini=<optimized out>, 
    rtld_fini=<optimized out>, stack_end=0x7fffffffe138) at ../csu/libc-start.c:344```

**Comment by VictorZuanazzi** [comment]
What is your gpu? I am having a similar problem with Pointnet2

**Comment by seangrate** [comment]
I was first experiencing it on a Quadro P400, but then also got the same error while using an RTX 2080Ti.

**Comment by VictorZuanazzi** [comment]
I raised an issue here: https://github.com/NVIDIAGameWorks/kaolin/issues/96

If you have a GeForce GTX 1080Ti or a TITAN X Pascal laying around (most of us don't really have this luxury!) I got it working with them. Maybe that is worth trying.

**Comment by Caenorst** [comment]
Hi, thank you for using Kaolin! The library went through a major rewrite with the version [0.9.0](https://github.com/NVIDIAGameWorks/kaolin/releases/tag/v0.9.0), and only the core library components we can thoroughly test and maintain are now part of this repository. Please refer to our latest documentation:
[https://kaolin.readthedocs.io/en/latest/](https://kaolin.readthedocs.io/en/latest/)

We are planning to release the improved model zoo as a separate repository, but cannot comment on the ETA at this time. Please Watch the github repository for updates.

Closing the bug as it is no longer relevant to this repo.
