### ISSUE TITLE
No module named 'kaolin.nnsearch'

### ISSUE THREAD

**Issue by jbartolozzi** [NVIDIAGameWorks/kaolin#40]
OS: Ubuntu 16.04.6
Nvidia Driver: 418.87
CUDA: 10.1

Steps to reproduce
```
conda create --name kaolin python=3.7
conda activate kaolin
conda install pytorch-gpu numpy
python setup.py install
python -c "import kaolin"
```
```
(kaolin) jbartolozzi@mldwl4028-l|kaolin|: python -c "import kaolin"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/jbartolozzi/kaolin/kaolin/__init__.py", line 17, in <module>
    from kaolin import conversions
  File "/home/jbartolozzi/kaolin/kaolin/conversions/__init__.py", line 1, in <module>
    from kaolin.conversions.meshconversions import *
  File "/home/jbartolozzi/kaolin/kaolin/conversions/meshconversions.py", line 22, in <module>
    from kaolin.metrics.point import directed_distance as directed_distance
  File "/home/jbartolozzi/kaolin/kaolin/metrics/__init__.py", line 2, in <module>
    from .point import *
  File "/home/jbartolozzi/kaolin/kaolin/metrics/point.py", line 16, in <module>
    from kaolin.nnsearch import nnsearch
ModuleNotFoundError: No module named 'kaolin.nnsearch'
```

**Comment by nikogamulin** [comment]
I had a similar problem while running python in kaolin base directory. If I run outside the kaolin directory, eveything works fine.

[Check issue #27 ](https://github.com/NVIDIAGameWorks/kaolin/issues/27)

**Comment by stephendb** [comment]
Unfortunately this makes the pytest's unusable since they seem to have hard coded relative paths to the root directory.

**Comment by Jean-Francois-Lafleche** [comment]
This error is occurring because the setup didn't compile the Cython function kaolin.nnsearch. After running setup, you probably saw the error `ModuleNotFoundError: No module named 'Cython'`. This does not occur with Python 3.6. 

Edit: on one of my tests, installing Cython manually did successfully compile nnsearch but did not resolve the import issue when in the root directory. Switching to Python 3.6 seems to be the only solution for now.

We will investigate a more permanent fix. Thank you for bringing it up and posting repro steps!

**Comment by christinezuzart** [comment]
OS: Windows 10
Cuda: 10.1
Python : 3.7.6
pytorch: 1.4.0

(kaolin) C:\ml_work\kaolin-master\kaolin-master>python
Python 3.7.6 (default, Jan  8 2020, 20:23:39) [MSC v.1916 64 bit (AMD64)] :: Anaconda, Inc. on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import kaolin as kal
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\ml_work\kaolin-master\kaolin-master\kaolin\__init__.py", line 17, in <module>
    from kaolin import conversions
  File "C:\ml_work\kaolin-master\kaolin-master\kaolin\conversions\__init__.py", line 1, in <module>
    from kaolin.conversions.meshconversions import *
  File "C:\ml_work\kaolin-master\kaolin-master\kaolin\conversions\meshconversions.py", line 22, in <module>
    from kaolin.metrics.point import directed_distance as directed_distance
  File "C:\ml_work\kaolin-master\kaolin-master\kaolin\metrics\__init__.py", line 2, in <module>
    from .point import *
  File "C:\ml_work\kaolin-master\kaolin-master\kaolin\metrics\point.py", line 16, in <module>
    from kaolin.nnsearch import nnsearch
ModuleNotFoundError: No module named 'kaolin.nnsearch'

I am getting this error.Any help to resolve this error.

**Comment by shumash** [comment]
Hi, thank you for using Kaolin! The library went through a major rewrite with the version [0.9.0](https://github.com/NVIDIAGameWorks/kaolin/releases/tag/v0.9.0), and this issue is no longer current. Please refer to our latest documentation:
[https://kaolin.readthedocs.io/en/latest/](https://kaolin.readthedocs.io/en/latest/)
