### ISSUE TITLE
Cuda compiling error

### ISSUE THREAD

**Issue by TritonSailor** [NVIDIAGameWorks/kaolin#44]
I'm getting this error when building kaolin on Win 10, with Cuda 10.2, Pytorch 1.3, Conda 3.7.

1 error detected in the compilation of "C:/Users/chris/AppData/Local/Temp/tmpxft_00000b28_00000000-10_sided_distance_cuda.cpp1.ii".
Traceback (most recent call last):
  File "C:\Users\chris\Anaconda3\envs\kaolin\lib\distutils\_msvccompiler.py", line 424, in compile
    self.spawn(args)
  File "C:\Users\chris\Anaconda3\envs\kaolin\lib\site-packages\torch\utils\cpp_extension.py", line 337, in spawn
    return original_spawn(cmd)
  File "C:\Users\chris\Anaconda3\envs\kaolin\lib\distutils\_msvccompiler.py", line 543, in spawn
    return super().spawn(cmd)
  File "C:\Users\chris\Anaconda3\envs\kaolin\lib\distutils\ccompiler.py", line 909, in spawn
    spawn(cmd, dry_run=self.dry_run)
  File "C:\Users\chris\Anaconda3\envs\kaolin\lib\distutils\spawn.py", line 38, in spawn
    _spawn_nt(cmd, search_path, dry_run=dry_run)
  File "C:\Users\chris\Anaconda3\envs\kaolin\lib\distutils\spawn.py", line 81, in _spawn_nt
    "command %r failed with exit status %d" % (cmd, rc))

**Comment by Jean-Francois-Lafleche** [comment]
Thanks for posting these details. Windows support is still considered experimental, but we are committed to solving these issues soon!

**Comment by TritonSailor** [comment]
Is there a known working windows configuration at this time?

**Comment by antmillar** [comment]
Hey, this is such a great repo just wondered when it might be available on windows?

**Comment by shumash** [comment]
Hi, thank you for using Kaolin! The library went through a major rewrite with the version [0.9.0](https://github.com/NVIDIAGameWorks/kaolin/releases/tag/v0.9.0), and this issue is no longer current. 

Please refer to our latest documentation and file a new bug if you have issues installing on Windows:
[https://kaolin.readthedocs.io/en/latest/](https://kaolin.readthedocs.io/en/latest/)
