### ISSUE TITLE
ImportError: cannot import name '_C' from 'kaolin'

### ISSUE THREAD

**Issue by ATiwariJP** [NVIDIAGameWorks/kaolin#503]
I need help with installation of Kaolin.

I am not able to install Kaolin as per the directions on - https://kaolin.readthedocs.io/en/latest/notes/installation.html

During the installation with the command "python setup.py develop", I run into the following error (I am providing here only a snippet) (View entire installation log here - 
[Installation_log.txt](https://github.com/NVIDIAGameWorks/kaolin/files/7775382/Installation_log.txt)) - 

```
raytrace_cuda.cu
ninja: build stopped: subcommand failed.
Traceback (most recent call last):
  File "C:\Users\akash\anaconda3\envs\kaolin2\lib\site-packages\torch\utils\cpp_extension.py", line 1539, in _run_ninja_build
    env=env)
  File "C:\Users\akash\anaconda3\envs\kaolin2\lib\subprocess.py", line 512, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['ninja', '-v']' returned non-zero exit status 1.
```

After the (failed) installation, I receive the output below for the following command line prompt - python -c "import kaolin; print(kaolin.__version__)"

```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Users\akash\OneDrive\Desktop\WINTER 2021\kaolin\kaolin\__init__.py", line 1, in <module>
    from . import io
  File "C:\Users\akash\OneDrive\Desktop\WINTER 2021\kaolin\kaolin\io\__init__.py", line 5, in <module>
    from . import render
  File "C:\Users\akash\OneDrive\Desktop\WINTER 2021\kaolin\kaolin\io\render.py", line 8, in <module>
    from ..render.camera import generate_perspective_projection
  File "C:\Users\akash\OneDrive\Desktop\WINTER 2021\kaolin\kaolin\render\__init__.py", line 2, in <module>
    from . import mesh
  File "C:\Users\akash\OneDrive\Desktop\WINTER 2021\kaolin\kaolin\render\mesh\__init__.py", line 1, in <module>
    from .utils import *
  File "C:\Users\akash\OneDrive\Desktop\WINTER 2021\kaolin\kaolin\render\mesh\utils.py", line 22, in <module>
    from ... import ops
  File "C:\Users\akash\OneDrive\Desktop\WINTER 2021\kaolin\kaolin\ops\__init__.py", line 1, in <module>
    from . import batch
  File "C:\Users\akash\OneDrive\Desktop\WINTER 2021\kaolin\kaolin\ops\batch.py", line 16, in <module>
    from kaolin import _C
ImportError: cannot import name '_C' from 'kaolin' (C:\Users\akash\OneDrive\Desktop\WINTER 2021\kaolin\kaolin\__init__.py)
```

**Comment by ATiwariJP** [comment]
The installation proceeded successfully without errors when I used `git checkout v0.9.0` to install an earlier version. 

I followed the instructions in the video here - https://www.youtube.com/watch?v=BwZ7s7DqbFs

**Comment by psx2** [comment]
This issue is still present today, and was never fixed.

**Comment by Caenorst** [comment]
I doubt it's the same issue since `deftet.cpp` have changed since. please specify your logs in the issue you have opened
