### ISSUE TITLE
Compilations of sided_distance_cuda.cu fails

### ISSUE THREAD

**Issue by andrearosasco** [NVIDIAGameWorks/kaolin#513]
Hello, 
I followed the steps in the installation guide but when I start compiling I get this error:
```
[18/30] C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.2\bin\nvcc --use-local-env -Xcompiler /MD -Xcompiler /wd4819 -Xcompiler /wd4251 -Xcompiler /wd4244 -Xcompiler /wd4267 -Xcompiler /wd4275 -Xcompiler /wd4018 -Xcompiler /wd4190 -Xcompiler /EHsc -Xcudafe --diag_suppress=base_class_has_different_dll_interface -Xcudafe --diag_suppress=field_without_dll_interface -Xcudafe --diag_suppress=dll_interface_conflict_none_assumed -Xcudafe --diag_suppress=dll_interface_conflict_dllexport_assumed -DWITH_CUDA -IC:\Users\arosasco\.conda\envs\kaolin\lib\site-packages\torch\include -IC:\Users\arosasco\.conda\envs\kaolin\lib\site-packages\torch\include\torch\csrc\api\include -IC:\Users\arosasco\.conda\envs\kaolin\lib\site-packages\torch\include\TH -IC:\Users\arosasco\.conda\envs\kaolin\lib\site-packages\torch\include\THC "-IC:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.2\include" "-IC:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.4\include\cub" -IC:\Users\arosasco\.conda\envs\kaolin\include -IC:\Users\arosasco\.conda\envs\kaolin\include -IC:\Users\arosasco\.conda\envs\kaolin\include -IC:\Users\arosasco\.conda\envs\kaolin\include "-IC:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Tools\MSVC\14.29.30133\ATLMFC\include" "-IC:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Tools\MSVC\14.29.30133\include" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\shared" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\um" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\winrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\cppwinrt" "-IC:\Program Files\robotology\yarp-3.1.0\include" "-IC:\Program Files\robotology\ACE-6.5.0_v14_x86_amd64" "-IC:\Program Files\robotology\Qt-5.11.1_v14_x86_amd64\include" "-IC:\Program Files (x86)\Windows Kits\10\Include\10.0.19041.0\shared" "-IC:\Program Files (x86)\Windows Kits\10\Include\10.0.19041.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\10\Lib\10.0.19041.0\um\x64" -c C:\Users\arosasco\python_libs\kaolin\kaolin\csrc\metrics\sided_distance_cuda.cu -o C:\Users\arosasco\python_libs\kaolin\build\temp.win-amd64-3.7\Release\kaolin/csrc\metrics\sided_distance_cuda.obj -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr -O3 -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=_C -D_GLIBCXX_USE_CXX11_ABI=0 -gencode=arch=compute_75,code=sm_75
C:/Users/arosasco/.conda/envs/kaolin/lib/site-packages/torch/include\c10/util/ThreadLocalDebugInfo.h(12): warning: modifier is ignored on an enum specifier

C:/Users/arosasco/.conda/envs/kaolin/lib/site-packages/torch/include\c10/util/ThreadLocalDebugInfo.h(12): warning: modifier is ignored on an enum specifier

sided_distance_cuda.cu
ninja: build stopped: subcommand failed.
Traceback (most recent call last):
  File "C:\Users\arosasco\.conda\envs\kaolin\lib\site-packages\torch\utils\cpp_extension.py", line 1539, in _run_ninja_build
    env=env)
  File "C:\Users\arosasco\.conda\envs\kaolin\lib\subprocess.py", line 512, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['ninja', '-v', '-j', '8']' returned non-zero exit status 1.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "setup.py", line 235, in <module>
    'build_ext': BuildExtension.with_options(no_python_abi_suffix=True)
  File "C:\Users\arosasco\.conda\envs\kaolin\lib\site-packages\setuptools\__init__.py", line 153, in setup
    return distutils.core.setup(**attrs)
  File "C:\Users\arosasco\.conda\envs\kaolin\lib\distutils\core.py", line 148, in setup
    dist.run_commands()
  File "C:\Users\arosasco\.conda\envs\kaolin\lib\distutils\dist.py", line 966, in run_commands
    self.run_command(cmd)
  File "C:\Users\arosasco\.conda\envs\kaolin\lib\distutils\dist.py", line 985, in run_command
    cmd_obj.run()
  File "C:\Users\arosasco\.conda\envs\kaolin\lib\site-packages\setuptools\command\develop.py", line 34, in run
    self.install_for_development()
  File "C:\Users\arosasco\.conda\envs\kaolin\lib\site-packages\setuptools\command\develop.py", line 114, in install_for_development
    self.run_command('build_ext')
  File "C:\Users\arosasco\.conda\envs\kaolin\lib\distutils\cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "C:\Users\arosasco\.conda\envs\kaolin\lib\distutils\dist.py", line 985, in run_command
    cmd_obj.run()
  File "C:\Users\arosasco\.conda\envs\kaolin\lib\site-packages\setuptools\command\build_ext.py", line 79, in run
    _build_ext.run(self)
  File "C:\Users\arosasco\.conda\envs\kaolin\lib\site-packages\Cython\Distutils\old_build_ext.py", line 186, in run
    _build_ext.build_ext.run(self)
  File "C:\Users\arosasco\.conda\envs\kaolin\lib\distutils\command\build_ext.py", line 340, in run
    self.build_extensions()
  File "C:\Users\arosasco\.conda\envs\kaolin\lib\site-packages\torch\utils\cpp_extension.py", line 670, in build_extensions
    build_ext.build_extensions(self)
  File "C:\Users\arosasco\.conda\envs\kaolin\lib\site-packages\Cython\Distutils\old_build_ext.py", line 195, in build_extensions
    _build_ext.build_ext.build_extensions(self)
  File "C:\Users\arosasco\.conda\envs\kaolin\lib\distutils\command\build_ext.py", line 449, in build_extensions
    self._build_extensions_serial()
  File "C:\Users\arosasco\.conda\envs\kaolin\lib\distutils\command\build_ext.py", line 474, in _build_extensions_serial
    self.build_extension(ext)
  File "C:\Users\arosasco\.conda\envs\kaolin\lib\site-packages\setuptools\command\build_ext.py", line 202, in build_extension
    _build_ext.build_extension(self, ext)
  File "C:\Users\arosasco\.conda\envs\kaolin\lib\distutils\command\build_ext.py", line 534, in build_extension
    depends=ext.depends)
  File "C:\Users\arosasco\.conda\envs\kaolin\lib\site-packages\torch\utils\cpp_extension.py", line 652, in win_wrap_ninja_compile
    with_cuda=with_cuda)
  File "C:\Users\arosasco\.conda\envs\kaolin\lib\site-packages\torch\utils\cpp_extension.py", line 1255, in _write_ninja_file_and_compile_objects
    error_prefix='Error compiling objects for extension')
  File "C:\Users\arosasco\.conda\envs\kaolin\lib\site-packages\torch\utils\cpp_extension.py", line 1555, in _run_ninja_build
    raise RuntimeError(message) from e
RuntimeError: Error compiling objects for extension
```
it seems the error originates in `sided_distance_cuda.cu` but I don't know how to find the exact line that is causing it.

**Comment by andrearosasco** [comment]
I just didn't set CUB_HOME correctly.
