### ISSUE TITLE
ModuleNotFoundError: No module named 'kaolin.nnsearch' 

### ISSUE THREAD

**Issue by Shabayek** [NVIDIAGameWorks/kaolin#52]
I'm using pytorch:19.10-py3 docker image (docker pull nvcr.io/nvidia/pytorch:19.10-py3). I get the following error:
.......

Finished processing dependencies for kaolin==0.2.0+a76a004
root@d404b78867d9:/workspace/kaolin# python
Python 3.6.9 |Anaconda, Inc.| (default, Jul 30 2019, 19:07:31) 
[GCC 7.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import kaolin as kal
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/workspace/kaolin/kaolin/__init__.py", line 17, in <module>
    from kaolin import conversions
  File "/workspace/kaolin/kaolin/conversions/__init__.py", line 1, in <module>
    from kaolin.conversions.meshconversions import *
  File "/workspace/kaolin/kaolin/conversions/meshconversions.py", line 22, in <module>
    from kaolin.metrics.point import directed_distance as directed_distance
  File "/workspace/kaolin/kaolin/metrics/__init__.py", line 2, in <module>
    from .point import *
  File "/workspace/kaolin/kaolin/metrics/point.py", line 16, in <module>
    from kaolin.nnsearch import nnsearch
ModuleNotFoundError: No module named 'kaolin.nnsearch'

**Comment by stephendb** [comment]
Same error. I installed pytorch using conda on ubuntu 18.04 as per the instructions.

**Comment by shersoni610** [comment]
I had the same issue but it seems to get resolved if I run the code outside the directory i.e. above
README,md folder.

**Comment by Shabayek** [comment]
@shersoni610 : I tried the same in both 1) the docker image and 2) a conda environment, but I get the following error:
In the docker image:
.....................
Using /opt/conda/lib/python3.6/site-packages
Finished processing dependencies for kaolin==0.2.0+a76a004
No CUDA runtime is found, using CUDA_HOME='/usr/local/cuda'
Traceback (most recent call last):
  File "kaolin/setup.py", line 192, in <module>
    ext_modules=cythonize(ext_modules),
  File "/opt/conda/lib/python3.6/site-packages/Cython/Build/Dependencies.py", line 897, in cythonize
    aliases=aliases)
  File "/opt/conda/lib/python3.6/site-packages/Cython/Build/Dependencies.py", line 777, in create_extension_list
    for file in nonempty(sorted(extended_iglob(filepattern)), "'%s' doesn't match any files" % filepattern):
  File "/opt/conda/lib/python3.6/site-packages/Cython/Build/Dependencies.py", line 102, in nonempty
    raise ValueError(error_msg)
ValueError: 'kaolin/cython/triangle_hash.pyx' doesn't match any files

For sure the cuda runtime exists as I'm working inside the docker image. Running nvcc --version:
root@870ec9066a81:/workspace# nvcc --version
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2019 NVIDIA Corporation
Built on Sun_Jul_28_19:07:16_PDT_2019
Cuda compilation tools, release 10.1, V10.1.243

On the other machine using conda environment:
The following error:
....................
Using /mnt/users/user/miniconda3/envs/kaoline/lib/python3.6/site-packages/decorator-4.4.1-py3.6.egg
Finished processing dependencies for kaolin==0.2.0+05e6433
Traceback (most recent call last):
  File "kaolin/setup.py", line 192, in <module>
    ext_modules=cythonize(ext_modules),
  File "/home/users/user/miniconda3/envs/kaoline/lib/python3.6/site-packages/Cython-0.29.14-py3.6-linux-x86_64.egg/Cython/Build/Dependencies.py", line 966, in cythonize
    aliases=aliases)
  File "/home/users/user/miniconda3/envs/kaoline/lib/python3.6/site-packages/Cython-0.29.14-py3.6-linux-x86_64.egg/Cython/Build/Dependencies.py", line 810, in create_extension_list
    for file in nonempty(sorted(extended_iglob(filepattern)), "'%s' doesn't match any files" % filepattern):
  File "/home/users/user/miniconda3/envs/kaoline/lib/python3.6/site-packages/Cython-0.29.14-py3.6-linux-x86_64.egg/Cython/Build/Dependencies.py", line 109, in nonempty
    raise ValueError(error_msg)
ValueError: 'kaolin/cython/triangle_hash.pyx' doesn't match any files

Running python (same result from the docker and the conda environment):
root@870ec9066a81:/workspace# python
Python 3.6.9 |Anaconda, Inc.| (default, Jul 30 2019, 19:07:31) 
[GCC 7.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import kaolin as kal
>>> print(kal.__version__)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: module 'kaolin' has no attribute '__version__'
>>> 

(kaoline) [user@194 ~]$ python
Python 3.6.9 |Anaconda, Inc.| (default, Jul 30 2019, 19:07:31) 
[GCC 7.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import kaolin as kal
>>> print(kal.__version__)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: module 'kaolin' has no attribute '__version__'
>>>

**Comment by Kuldaen** [comment]
> I had the same issue but it seems to get resolved if I run the code outside the directory i.e. above
> README,md folder.

I'm getting the same and this also fixes it for me.

**Comment by Kuldaen** [comment]
Actually it seems to work as long as it is in any folder besides the root of the git repository. ie I can go into `examples` and it is fine

**Comment by Shabayek** [comment]
@Kuldaen : I tried again from another folder beside the root of kaolin but I still get the same error:
....................
Finished processing dependencies for kaolin==0.2.0+05e6433
Traceback (most recent call last):
  File "../kaolin/setup.py", line 192, in <module>
    ext_modules=cythonize(ext_modules),
  File "/home/users/user/miniconda3/envs/kaoline/lib/python3.6/site-packages/Cython-0.29.14-py3.6-linux-x86_64.egg/Cython/Build/Dependencies.py", line 966, in cythonize
    aliases=aliases)
  File "/home/users/user/miniconda3/envs/kaoline/lib/python3.6/site-packages/Cython-0.29.14-py3.6-linux-x86_64.egg/Cython/Build/Dependencies.py", line 810, in create_extension_list
    for file in nonempty(sorted(extended_iglob(filepattern)), "'%s' doesn't match any files" % filepattern):
  File "/home/users/user/miniconda3/envs/kaoline/lib/python3.6/site-packages/Cython-0.29.14-py3.6-linux-x86_64.egg/Cython/Build/Dependencies.py", line 109, in nonempty
    raise ValueError(error_msg)
ValueError: 'kaolin/cython/triangle_hash.pyx' doesn't match any files

**Comment by Kuldaen** [comment]
Sorry but cythonize error is something different from the nnsearch problem. You should create a new issue.

**Comment by Shabayek** [comment]
It is a follow up which happens when I start the installation from the parent directory of kaolin or another directory in the same level of kaolin. Otherwise, there is the no module named 'kaolin.nnsearch' error. Please recall that the instructions are to install from the kaolin directory. I created issue #60 for the new error.

**Comment by Kuldaen** [comment]
you can't run the installation from outside or in another directory. it has to be in the root of the git repository. you only have to run this once per virtual enviroment.

the nnsearch problem is separate, once you have installed it properly from there, you only need to run any python scripts that use kaolin from another directory.

**Comment by Shabayek** [comment]
If I run the code from outside the directory I get the following error:
(kaoline) [user@access1 ~]$ python
Python 3.6.9 |Anaconda, Inc.| (default, Jul 30 2019, 19:07:31) 
[GCC 7.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import kaolin as kal
>>> print(kal.__version__)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: module 'kaolin' has no attribute '__version__'
>>> 

(kaoline) [user@access1 ~]$ python kaolin/examples/Classification/pointcloud_classification.py
Traceback (most recent call last):
  File "kaolin/examples/Classification/pointcloud_classification.py", line 5, in <module>
    import kaolin as kal
ModuleNotFoundError: No module named 'kaolin'

**Comment by Kuldaen** [comment]
it should be `print(kal.__version__)`

**Comment by Shabayek** [comment]
>>> import kaolin as kal
>>> print(kal.__version__)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: module 'kaolin' has no attribute '__version__'
>>>

**Comment by Shabayek** [comment]
>>> import kaolin as kal
>>> print(kal.__version__)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: module 'kaolin' has no attribute '__version__'
>>>

**Comment by Shabayek** [comment]
This is what I'm doing but the underscores are automatically removed by the editor!!

Follows another example:
(kaoline) [user@access1 ~]$ python kaolin/examples/Classification/pointcloud_classification.py
Traceback (most recent call last):
  File "kaolin/examples/Classification/pointcloud_classification.py", line 5, in <module>
    import kaolin as kal
ModuleNotFoundError: No module named 'kaolin'

**Comment by Caenorst** [comment]
Hi, thank you for using Kaolin! The library went through a major rewrite with the version [0.9.0](https://github.com/NVIDIAGameWorks/kaolin/releases/tag/v0.9.0), and only the core library components we can thoroughly test and maintain are now part of this repository. Please refer to our latest documentation:
[https://kaolin.readthedocs.io/en/latest/](https://kaolin.readthedocs.io/en/latest/)

Closing the bug as it is no longer relevant to this repo.
