### ISSUE TITLE
ValueError: 'kaolin/cython/triangle_hash.pyx' doesn't match any files

### ISSUE THREAD

**Issue by Shabayek** [NVIDIAGameWorks/kaolin#60]
This error happens if the installation takes place from the parent directory of kaolin or another directory in the same level of it (see issue #52 ):
....................
Finished processing dependencies for kaolin==0.2.0+05e6433
Traceback (most recent call last):
File "../kaolin/setup.py", line 192, in
ext_modules=cythonize(ext_modules),
File "/home/users/user/miniconda3/envs/kaoline/lib/python3.6/site-packages/Cython-0.29.14-py3.6-linux-x86_64.egg/Cython/Build/Dependencies.py", line 966, in cythonize
aliases=aliases)
File "/home/users/user/miniconda3/envs/kaoline/lib/python3.6/site-packages/Cython-0.29.14-py3.6-linux-x86_64.egg/Cython/Build/Dependencies.py", line 810, in create_extension_list
for file in nonempty(sorted(extended_iglob(filepattern)), "'%s' doesn't match any files" % filepattern):
File "/home/users/user/miniconda3/envs/kaoline/lib/python3.6/site-packages/Cython-0.29.14-py3.6-linux-x86_64.egg/Cython/Build/Dependencies.py", line 109, in nonempty
raise ValueError(error_msg)
ValueError: 'kaolin/cython/triangle_hash.pyx' doesn't match any files

**Comment by Shabayek** [comment]
It has to be installed from the kaolin root directory.
