### ISSUE TITLE
Install errors

### ISSUE THREAD

**Issue by JTT94** [NVIDIAGameWorks/kaolin#668]
I have a docker file that used to work, to install kaolin I had this entry

`RUN git clone https://github.com/NVIDIAGameWorks/kaolin.git && \
    cd ./kaolin && \
    IGNORE_TORCH_VER=1 /root/conda/envs/env/bin/python setup.py develop && \
    cd .. `

This no longer works for some unknown reason, maybe changes to kaolin?

I get the following error
`Cloning into 'kaolin'...
Traceback (most recent call last):
  File "setup.py", line 31, in <module>
    import torch
  File "/root/conda/envs/env/lib/python3.8/site-packages/torch/__init__.py", line 649, in <module>
    from ._tensor import Tensor
  File "/root/conda/envs/env/lib/python3.8/site-packages/torch/_tensor.py", line 12, in <module>
    import torch.utils.hooks as hooks
  File "/root/conda/envs/env/lib/python3.8/site-packages/torch/utils/__init__.py", line 6, in <module>
    from .cpp_backtrace import get_cpp_backtrace
  File "/root/conda/envs/env/lib/python3.8/site-packages/torch/utils/cpp_backtrace.py", line 1, in <module>
    from torch._C import _get_cpp_backtrace
ImportError: cannot import name '_get_cpp_backtrace' from 'torch._C' (/root/conda/envs/env/lib/python3.8/site-packages/torch/_C.cpython-38-x86_64-linux-gnu.so)`

Have others run into this issue? Is there a working example of including kaolin in a dockerfile?

**Comment by JTT94** [comment]
My own fault. Conda env had issues

**Comment by zwshan** [comment]
hello could you please tell me how to solve it?
