### ISSUE TITLE
kaolin/_C.so: undefined symbol: _ZN3c106detail19maybe_wrap_dim_slowEllb

### ISSUE THREAD

**Issue by kenorb** [NVIDIAGameWorks/kaolin#678]
```
code$ python3.9 main.py 
Traceback (most recent call last):
  File "2dimageto3dmodel/code/main.py", line 21, in <module>
    from rendering.mesh_template import MeshTemplate
  File "2dimageto3dmodel/code/rendering/mesh_template.py", line 1, in <module>
    import kaolin as kal
  File "/usr/local/lib/python3.9/dist-packages/kaolin/__init__.py", line 1, in <module>
    from . import io
  File "/usr/local/lib/python3.9/dist-packages/kaolin/io/__init__.py", line 5, in <module>
    from . import render
  File "/usr/local/lib/python3.9/dist-packages/kaolin/io/render.py", line 23, in <module>
    from ..render.camera import generate_perspective_projection
  File "/usr/local/lib/python3.9/dist-packages/kaolin/render/__init__.py", line 2, in <module>
    from . import mesh
  File "/usr/local/lib/python3.9/dist-packages/kaolin/render/mesh/__init__.py", line 1, in <module>
    from .utils import *
  File "/usr/local/lib/python3.9/dist-packages/kaolin/render/mesh/utils.py", line 22, in <module>
    from ... import ops
  File "/usr/local/lib/python3.9/dist-packages/kaolin/ops/__init__.py", line 1, in <module>
    from . import batch
  File "/usr/local/lib/python3.9/dist-packages/kaolin/ops/batch.py", line 17, in <module>
    from kaolin import _C
ImportError: /usr/local/lib/python3.9/dist-packages/kaolin/_C.so: undefined symbol: _ZN3c106detail19maybe_wrap_dim_slowEllb
```

I've tried to install different versions of torch and torchvision (0.10.0-0.14.1) with no luck.

Installed `kaolin` by:

```
% python3.9 -m pip install kaolin==0.12.0 --use-deprecated=html5lib -f https://nvidia-kaolin.s3.us-east-2.amazonaws.com/torch-1.12.1_cu113.html
```

**Comment by Caenorst** [comment]
Hi @kenorb , usually this kind of error happens when the torch version (including the cuda version) is not matching with the wheels you are selecting, can you verify that your torch version is `1.12.1+cu113` ?

**Comment by samiede** [comment]
I have a similar issue:
```ImportError: /home/ubuntu/miniconda3/envs/kaolin/lib/python3.7/site-packages/kaolin/_C.so: undefined symbol: _ZNK3c1010TensorImpl36is_contiguous_nondefault_policy_implENS_12MemoryFormatE```

I have cuda 11.6 and torch 1.12.1 installed, so I use
`pip install kaolin==0.11.0 -f https://nvidia-kaolin.s3.us-east-2.amazonaws.com/torch-1.12.1_cu116.html` but no avail.

**Comment by Caenorst** [comment]
Hi @samiede , please open a new issue, I'll try to help you. Again usually this kind of errors happen when there is a difference in torch version and kaolin's torch version (including cuda)

**Comment by wangsen1312** [comment]
similar problem here, any update on this?

**Comment by Caenorst** [comment]
Hi @wangsen1312 what is your error message, what is your torch version, what it your cuda version, what is your command-line?

**Comment by wangsen1312** [comment]
error message:
`ImportError: /home/senw/anaconda3/envs/texture/lib/python3.9/site-packages/kaolin/_C.so: undefined symbol: _ZNK2at6Tensor8data_ptrIhEEPT_v`

the  pytorch version is 1.12.1 and cuda version is  11.3

I just check the kaolin version
` python -c "import kaolin; print(kaolin.__version__)"`

**Comment by Caenorst** [comment]
what was the command line to install kaolin?
also double check `torch.__version__` and `torch.version.cuda`

**Comment by wangsen1312** [comment]
@Caenorst Thank you for your prompt response.
I install kaolin with `pip install kaolin==0.11.0 -f https://nvidia-kaolin.s3.us-east-2.amazonaws.com/torch-1.12.1_cu11.3.html`

I just double check the `torch.__ version__ ` and `torch.version.cuda`. it is 1.12.1 and 11.3

**Comment by Caenorst** [comment]
There is a typo in your installation command-line it should be `https://nvidia-kaolin.s3.us-east-2.amazonaws.com/torch-1.12.1_cu113.html`

**Comment by wangsen1312** [comment]
> There is a typo in your installation command-line it should be `https://nvidia-kaolin.s3.us-east-2.amazonaws.com/torch-1.12.1_cu113.html`

sorry for the typo. The error still exists

**Comment by Caenorst** [comment]
Actually looking at https://nvidia-kaolin.s3.us-east-2.amazonaws.com/torch-1.12.1_cu113.html there is no kaolin 0.11.0, do you need specifically 0.11.0 ? I suggest use the latest version

**Comment by wangsen1312** [comment]
@Caenorst Thank you for your support. it works now!
