### ISSUE TITLE
ValueError: numpy.ndarray has the wrong size, try recompiling. Expected 80, got 88

### ISSUE THREAD

**Issue by S-kewen** [NVIDIAGameWorks/kaolin#744]
First of all, I would like to thank the author for his contribution.

We've had some issues recently and don't know how to fix them. When we try to install kaolin we encounter some errors.

>>> import kaolin as kal
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/skewen/test/kaolin/kaolin/__init__.py", line 17, in <module>
    from kaolin import conversions
  File "/home/skewen/test/kaolin/kaolin/conversions/__init__.py", line 1, in <module>
    from kaolin.conversions.meshconversions import *
  File "/home/skewen/test/kaolin/kaolin/conversions/meshconversions.py", line 20, in <module>
    from kaolin.metrics.point import directed_distance as directed_distance
  File "/home/skewen/test/kaolin/kaolin/metrics/__init__.py", line 2, in <module>
    from .point import *
  File "/home/skewen/test/kaolin/kaolin/metrics/point.py", line 16, in <module>
    from kaolin.nnsearch import nnsearch
  File "__init__.pxd", line 199, in init kaolin.nnsearch
ValueError: numpy.ndarray has the wrong size, try recompiling. Expected 80, got 88
>>> print(kal.__version__)
Traceback (most recent call last):

**Comment by Caenorst** [comment]
Hi @S-kewen it looks like you are using Kaolin v0.1?

It could be a dependency update breaking things.

**Comment by shumash** [comment]
Looks like this is an old version of the library. We no longer support v0.1.
