### ISSUE TITLE
Problem installing Kaolin - README.md

### ISSUE THREAD

**Issue by Kallamamran** [NVIDIAGameWorks/kaolin#847]
It complains on teh README.md file missing and doesn't install. It's really stupid if the whole installation malfunctions because of a readme-file 😒

```
(venv) C:\Comfy3D>pip install kaolin==0.17.0 -f https://nvidia-kaolin.s3.us-east-2.amazonaws.com/torch-2.5.1_cu124.html
Looking in links: https://nvidia-kaolin.s3.us-east-2.amazonaws.com/torch-2.5.1_cu124.html
Collecting kaolin==0.17.0
  Downloading https://nvidia-kaolin.s3.us-east-2.amazonaws.com/torch-2.5.1_cu124/kaolin-0.17.0-cp312-cp312-win_amd64.whl (5.2 MB)
     ---------------------------------------- 5.2/5.2 MB 3.3 MB/s eta 0:00:00
Collecting ipycanvas (from kaolin==0.17.0)
  Using cached ipycanvas-0.13.3-py2.py3-none-any.whl.metadata (6.3 kB)
Collecting ipyevents (from kaolin==0.17.0)
  Using cached ipyevents-2.0.2-py3-none-any.whl.metadata (2.9 kB)
Collecting jupyter-client<8 (from kaolin==0.17.0)
  Using cached jupyter_client-7.4.9-py3-none-any.whl.metadata (8.5 kB)
Collecting flask (from kaolin==0.17.0)
  Using cached flask-3.1.0-py3-none-any.whl.metadata (2.7 kB)
Collecting tornado (from kaolin==0.17.0)
  Using cached tornado-6.4.2-cp38-abi3-win_amd64.whl.metadata (2.6 kB)
Collecting comm>=0.1.3 (from kaolin==0.17.0)
  Using cached comm-0.2.2-py3-none-any.whl.metadata (3.7 kB)
Collecting usd-core (from kaolin==0.17.0)
  Using cached usd_core-24.11-cp312-none-win_amd64.whl.metadata (1.6 kB)
Requirement already satisfied: numpy<2.0 in c:\comfy3d\venv\lib\site-packages (from kaolin==0.17.0) (1.26.4)
Collecting pybind11 (from kaolin==0.17.0)
  Using cached pybind11-2.13.6-py3-none-any.whl.metadata (9.5 kB)
Requirement already satisfied: Pillow>=8.0.0 in c:\comfy3d\venv\lib\site-packages (from kaolin==0.17.0) (11.0.0)
Requirement already satisfied: tqdm>=4.51.0 in c:\comfy3d\venv\lib\site-packages (from kaolin==0.17.0) (4.67.1)
Requirement already satisfied: scipy in c:\comfy3d\venv\lib\site-packages (from kaolin==0.17.0) (1.14.1)
Collecting pygltflib (from kaolin==0.17.0)
  Using cached pygltflib-1.16.3.tar.gz (42 kB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [7 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "C:\Temp\pip-install-m4179s7e\pygltflib_d2008f9c5e0c4e93afb0934777f7450a\setup.py", line 15, in <module>
          with open("README.md", "r", encoding='utf-8') as fh:
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      FileNotFoundError: [Errno 2] No such file or directory: 'README.md'
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

(venv) C:\Comfy3D>pip show kaolin
WARNING: Package(s) not found: kaolin
```

```
venv) C:\Comfy3D>nvcc --version
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2024 NVIDIA Corporation
Built on Tue_Feb_27_16:28:36_Pacific_Standard_Time_2024
Cuda compilation tools, release 12.4, V12.4.99
Build cuda_12.4.r12.4/compiler.33961263_0
```

```
(venv) C:\Comfy3D>pip show torch
Name: torch
Version: 2.5.1+cu124
Summary: Tensors and Dynamic neural networks in Python with strong GPU acceleration
Home-page: https://pytorch.org/
Author: PyTorch Team
Author-email: packages@pytorch.org
License: BSD-3-Clause
Location: C:\Comfy3D\venv\Lib\site-packages
Requires: filelock, fsspec, jinja2, networkx, setuptools, sympy, typing-extensions
Required-by: kornia, spandrel, torchaudio, torchsde, torchvision, xformers
```

**Comment by Caenorst** [comment]
Hi @Kallamamran thanks for your interest in Kaolin. From the paths, I assume you are using Windows?
