### ISSUE TITLE
CUDA&ImportError:load_textures...undefined symbol: cudaSetupArgument

### ISSUE THREAD

**Issue by yqdch** [NVIDIAGameWorks/kaolin#88]
I got this error when importing kaolin on Ubuntu16.04, with Cuda 10.1,python 3.6
>>> import kaolin
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/miniconda3/envs/kaolin/lib/python3.6/site-packages/kaolin-0.1.0-py3.6-linux-x86_64.egg/kaolin/__init__.py", line 17, in <module>
  File "/usr/local/miniconda3/envs/kaolin/lib/python3.6/site-packages/kaolin-0.1.0-py3.6-linux-x86_64.egg/kaolin/conversions/__init__.py", line 1, in <module>
  File "/usr/local/miniconda3/envs/kaolin/lib/python3.6/site-packages/kaolin-0.1.0-py3.6-linux-x86_64.egg/kaolin/conversions/meshconversions.py", line 22, in <module>
  File "/usr/local/miniconda3/envs/kaolin/lib/python3.6/site-packages/kaolin-0.1.0-py3.6-linux-x86_64.egg/kaolin/metrics/__init__.py", line 3, in <module>
  File "/usr/local/miniconda3/envs/kaolin/lib/python3.6/site-packages/kaolin-0.1.0-py3.6-linux-x86_64.egg/kaolin/metrics/mesh.py", line 40, in <module>
  File "/usr/local/miniconda3/envs/kaolin/lib/python3.6/site-packages/kaolin-0.1.0-py3.6-linux-x86_64.egg/kaolin/rep/__init__.py", line 1, in <module>
  File "/usr/local/miniconda3/envs/kaolin/lib/python3.6/site-packages/kaolin-0.1.0-py3.6-linux-x86_64.egg/kaolin/rep/Mesh.py", line 27, in <module>
  File "/usr/local/miniconda3/envs/kaolin/lib/python3.6/site-packages/kaolin-0.1.0-py3.6-linux-x86_64.egg/kaolin/cuda/load_textures.py", line 7, in <module>
  File "/usr/local/miniconda3/envs/kaolin/lib/python3.6/site-packages/kaolin-0.1.0-py3.6-linux-x86_64.egg/kaolin/cuda/load_textures.py", line 6, in __bootstrap__
  File "/usr/local/miniconda3/envs/kaolin/lib/python3.6/imp.py", line 342, in load_dynamic
    return _load(spec)
ImportError: /root/.cache/Python-Eggs/kaolin-0.1.0-py3.6-linux-x86_64.egg-tmp/kaolin/cuda/load_textures.cpython-36m-x86_64-linux-gnu.so: undefined symbol: cudaSetupArgument

**Comment by yqdch** [comment]
**Reason**
The CUDA running environment  is different from that for compiling the code.

**Solution**
cd kaolin
rm -rf build

Add these code below the .bashrc
export LD_LIBRARY_PATH="/usr/local/cuda-10.1/lib64":$LD_LIBRARY_PATH
export PATH="/usr/local/cuda-10.1/bin":$PATH

create a new terminal
cd kaolin
python setup.py install

**Comment by nguyenmichau** [comment]
Hello,

I have the same problem as you did. However, I'm on Windows 10, CUDA 10.0, Python 3.6

```
>>> import kaolin as kal
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\hong\Anaconda3\envs\kaolin\lib\site-packages\kaolin-0.1.0-py3.6-win-amd64.egg\kaolin\__init__.py", line 17, in <module>
  File "C:\Users\hong\Anaconda3\envs\kaolin\lib\site-packages\kaolin-0.1.0-py3.6-win-amd64.egg\kaolin\conversions\__init__.py", line 1, in <module>
  File "C:\Users\hong\Anaconda3\envs\kaolin\lib\site-packages\kaolin-0.1.0-py3.6-win-amd64.egg\kaolin\conversions\meshconversions.py", line 22, in <module>
  File "C:\Users\hong\Anaconda3\envs\kaolin\lib\site-packages\kaolin-0.1.0-py3.6-win-amd64.egg\kaolin\metrics\__init__.py", line 3, in <module>
  File "C:\Users\hong\Anaconda3\envs\kaolin\lib\site-packages\kaolin-0.1.0-py3.6-win-amd64.egg\kaolin\metrics\mesh.py", line 40, in <module>
  File "C:\Users\hong\Anaconda3\envs\kaolin\lib\site-packages\kaolin-0.1.0-py3.6-win-amd64.egg\kaolin\rep\__init__.py", line 1, in <module>
  File "C:\Users\hong\Anaconda3\envs\kaolin\lib\site-packages\kaolin-0.1.0-py3.6-win-amd64.egg\kaolin\rep\Mesh.py", line 27, in <module>
  File "C:\Users\hong\Anaconda3\envs\kaolin\lib\site-packages\kaolin-0.1.0-py3.6-win-amd64.egg\kaolin\cuda\load_textures.py", line 7, in <module>
  File "C:\Users\hong\Anaconda3\envs\kaolin\lib\site-packages\kaolin-0.1.0-py3.6-win-amd64.egg\kaolin\cuda\load_textures.py", line 6, in __bootstrap__
  File "C:\Users\hong\Anaconda3\envs\kaolin\lib\imp.py", line 343, in load_dynamic
    return _load(spec)
ImportError: DLL load failed: Le module spécifié est introuvable.
```
I tried to follow your solution by doing the equivalent on Windows. I did: 'del build' and then added the paths to my environment variables. I'm not sure if I did what you said correctly but I still end up with the same error.

Could you please help?
Thank you very much
