### ISSUE TITLE
ModuleNotFoundError: No module named 'kaolin.nnsearch'

### ISSUE THREAD

**Issue by michel84** [NVIDIAGameWorks/kaolin#9]
The installation of kaolin "python setup.py install" runs smoothly, but when I test the installation by running "python -c 'import kaolin'" I get the following error:

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Data02/michel/MyResearch/kaolin/kaolin/__init__.py", line 17, in <module>
    from kaolin import conversions
  File "/Data02/michel/MyResearch/kaolin/kaolin/conversions/__init__.py", line 1, in <module>
    from kaolin.conversions.meshconversions import *
  File "/Data02/michel/MyResearch/kaolin/kaolin/conversions/meshconversions.py", line 22, in <module>
    from kaolin.metrics.point import directed_distance as directed_distance
  File "/Data02/michel/MyResearch/kaolin/kaolin/metrics/__init__.py", line 2, in <module>
    from .point import *
  File "/Data02/michel/MyResearch/kaolin/kaolin/metrics/point.py", line 16, in <module>
    from kaolin.nnsearch import nnsearch
ModuleNotFoundError: No module named 'kaolin.nnsearch'

Any ideas about what is causing this issue?

**Comment by dkasuga** [comment]
I have exactly the same problem.

**Comment by momoani** [comment]
You just have to go up a directory (out of the /kaolin/ directory).

**Comment by michel84** [comment]
Great @momoani, it worked.
