### ISSUE TITLE
PointNet2Segmenter raises CUDA error: an illegal memory access was encountered

### ISSUE THREAD

**Issue by VictorZuanazzi** [NVIDIAGameWorks/kaolin#92]
Hello,

I am trying to use the PointNet2Segmenter, but that is giving some unnexpected issues.

The following code runs on a GeForce GTX 1080 Ti:

```
import torch
from torch.optim import Adam
from kaolin.models.PointNet2 import PointNet2Segmenter, PointNet2Classifier

device = "cuda" if torch.cuda.is_available() else "cpu"

model = PointNet2Segmenter(in_features=4,  # F
                           num_classes=2,  # K
                           use_xyz_feature=True,
                           use_random_ball_query=True).to(device)

print(device)

opt = Adam(model.parameters())
opt.zero_grad()

fake_cloud = torch.rand(16, 128, 7, device=device)  # (B, N, F+C)

segmented = model(fake_cloud)  # (B, N, K)

target = torch.rand_like(segmented, device=device)  # (B, N, K)

loss = torch.nn.MSELoss()(segmented, target)
loss.backward()
```
However, when I add the **optimizer step**, I get an illigal memory access:
```
import torch
from torch.optim import Adam
from kaolin.models.PointNet2 import PointNet2Segmenter, PointNet2Classifier

device = "cuda" if torch.cuda.is_available() else "cpu"

model = PointNet2Segmenter(in_features=4,  # F
                           num_classes=2,  # K
                           use_xyz_feature=True,
                           use_random_ball_query=True).to(device)

print(device)

opt = Adam(model.parameters())
opt.zero_grad()

fake_cloud = torch.rand(16, 128, 7, device=device)  # (B, N, F+C)

segmented = model(fake_cloud)  # (B, N, K)

target = torch.rand_like(segmented, device=device)  # (B, N, K)

loss = torch.nn.MSELoss()(segmented, target)
loss.backward()
opt.step()

print(segmented.shape)
```

```
Traceback (most recent call last):
  File "/home/zuanazzi/PointCloudFlow/pn2_test.py", line 25, in <module>
    opt.step()
  File "/home/zuanazzi/anaconda3/envs/kaolin/lib/python3.6/site-packages/torch/optim/adam.py", line 96, in step
    exp_avg_sq.mul_(beta2).addcmul_(1 - beta2, grad, grad)
RuntimeError: CUDA error: an illegal memory access was encountered
```

Any ideas of what the problem may be? Any chance it is something I am doing wrong?

**Comment by VictorZuanazzi** [comment]
Two small findings that may save people a lot of debugging time:

torch.optim.SGD and ASGD seem to work, the other optimizers output similar error messages.

```
# opt = Adam(model.parameters())          # BREAKS
opt = SGD(model.parameters(), lr=0.01)  # works!
# opt = Adadelta(model.parameters())      # BREAKS
# opt = Adagrad(model.parameters())       # BREAKS
# opt = Adamax(model.parameters())        # BREAKS
# opt = AdamW(model.parameters())         # BREAKS
# opt = ASGD(model.parameters())          # works!
# opt = RMSprop(model.parameters())       # BREAKS
# opt = Rprop(model.parameters())         # BREAKS
```

Logging the loss of the model does not seem possible! _(should that be a separate issue?)_
`print(loss.item())`
The line above raises the another illegal memory access:
```
Traceback (most recent call last):
  File "/home/zuanazzi/home/zuanazzi/PointCloudFlow/pn2_test.py", line 55, in <module>
    print(loss.item())
RuntimeError: CUDA error: an illegal memory access was encountered
```

**Comment by Caenorst** [comment]
Hi, thank you for using Kaolin! The library went through a major rewrite with the version [0.9.0](https://github.com/NVIDIAGameWorks/kaolin/releases/tag/v0.9.0), and only the core library components we can thoroughly test and maintain are now part of this repository. Please refer to our latest documentation:
[https://kaolin.readthedocs.io/en/latest/](https://kaolin.readthedocs.io/en/latest/)

We are planning to release the improved model zoo as a separate repository, but cannot comment on the ETA at this time. Please Watch the github repository for updates.

Closing the bug as it is no longer relevant to this repo.
