### ISSUE TITLE
Textures in DIB-R

### ISSUE THREAD

**Issue by tejank10** [NVIDIAGameWorks/kaolin#97]
Hello there! I was trying out the DIB-R example. I want to render it with texture file. I could understand how texture can be use in NMR and SoftRas but it is not clear in case of DIB-R example. `color` is not an optional argument for DIB-R renderer. In that case, how do I pass the colors of texture? I am having `.mtl` file for material and and an image for texture.

**Comment by tejank10** [comment]
I also tried rendering using the approach described [here](https://github.com/NVIDIAGameWorks/kaolin/blob/master/kaolin/graphics/dib_renderer/test/test_tex.py). That led to:

```
Traceback (most recent call last):
  File "example.py", line 114, in <module>
    main()
  File "example.py", line 106, in main
    predictions, _, _ = renderer(points=[vertices, faces[0].long()], colors=[uvs, face_textures[0], textures])
  File "/home/tejan/.conda/envs/kaolin_new/lib/python3.6/site-packages/torch/nn/modules/module.py", line 541, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/tejan/.conda/envs/kaolin_new/lib/python3.6/site-packages/kaolin-0.1.0-py3.6-linux-x86_64.egg/kaolin/graphics/dib_renderer/renderer/base.py", line 65, in forward
  File "/home/tejan/.conda/envs/kaolin_new/lib/python3.6/site-packages/torch/nn/modules/module.py", line 541, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/tejan/.conda/envs/kaolin_new/lib/python3.6/site-packages/kaolin-0.1.0-py3.6-linux-x86_64.egg/kaolin/graphics/dib_renderer/renderer/texrender.py", line 77, in forward
  File "/home/tejan/.conda/envs/kaolin_new/lib/python3.6/site-packages/kaolin-0.1.0-py3.6-linux-x86_64.egg/kaolin/graphics/dib_renderer/rasterizer/rasterizer.py", line 101, in forward

RuntimeError: CUDA error: device-side assert triggered
The above operation failed in interpreter, with the following stack trace:
at <string>:3:9

def mul(a : float, b : Tensor) -> Tensor:
  return b * a
         ~~~~~ <--- HERE
def add(a : float, b : Tensor) -> Tensor:
  return b + a
def ne(a : float, b : Tensor) -> Tensor:
  return b != a
def eq(a : float, b : Tensor) -> Tensor:
  return b == a
def lt(a : float, b : Tensor) -> Tensor:
  return b > a
def le(a : float, b : Tensor) -> Tensor:

Drawing:   0%|                                                                                                         | 0/90 [00:00<?, ?it/s]
/opt/conda/conda-bld/pytorch_1573049304260/work/aten/src/ATen/native/cuda/IndexKernel.cu:60: lambda [](int)->auto::operator()(int)->auto: block: [28,0,0], thread: [16,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
/opt/conda/conda-bld/pytorch_1573049304260/work/aten/src/ATen/native/cuda/IndexKernel.cu:60: lambda [](int)->auto::operator()(int)->auto: block: [28,0,0], thread: [17,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
/opt/conda/conda-bld/pytorch_1573049304260/work/aten/src/ATen/native/cuda/IndexKernel.cu:60: lambda [](int)->auto::operator()(int)->auto: block: [28,0,0], thread: [18,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
/opt/conda/conda-bld/pytorch_1573049304260/work/aten/src/ATen/native/cuda/IndexKernel.cu:60: lambda [](int)->auto::operator()(int)->auto: block: [28,0,0], thread: [19,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
/opt/conda/conda-bld/pytorch_1573049304260/work/aten/src/ATen/native/cuda/IndexKernel.cu:60: lambda [](int)->auto::operator()(int)->auto: block: [28,0,0], thread: [20,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
/opt/conda/conda-bld/pytorch_1573049304260/work/aten/src/ATen/native/cuda/IndexKernel.cu:60: lambda [](int)->auto::operator()(int)->auto: block: [28,0,0], thread: [21,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
/opt/conda/conda-bld/pytorch_1573049304260/work/aten/src/ATen/native/cuda/IndexKernel.cu:60: lambda [](int)->auto::operator()(int)->auto: block: [28,0,0], thread: [22,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
/opt/conda/conda-bld/pytorch_1573049304260/work/aten/src/ATen/native/cuda/IndexKernel.cu:60: lambda [](int)->auto::operator()(int)->auto: block: [28,0,0], thread: [23,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
/opt/conda/conda-bld/pytorch_1573049304260/work/aten/src/ATen/native/cuda/IndexKernel.cu:60: lambda [](int)->auto::operator()(int)->auto: block: [28,0,0], thread: [24,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
/opt/conda/conda-bld/pytorch_1573049304260/work/aten/src/ATen/native/cuda/IndexKernel.cu:60: lambda [](int)->auto::operator()(int)->auto: block: [28,0,0], thread: [25,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
/opt/conda/conda-bld/pytorch_1573049304260/work/aten/src/ATen/native/cuda/IndexKernel.cu:60: lambda [](int)->auto::operator()(int)->auto: block: [28,0,0], thread: [26,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
/opt/conda/conda-bld/pytorch_1573049304260/work/aten/src/ATen/native/cuda/IndexKernel.cu:60: lambda [](int)->auto::operator()(int)->auto: block: [28,0,0], thread: [27,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
/opt/conda/conda-bld/pytorch_1573049304260/work/aten/src/ATen/native/cuda/IndexKernel.cu:60: lambda [](int)->auto::operator()(int)->auto: block: [28,0,0], thread: [28,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
/opt/conda/conda-bld/pytorch_1573049304260/work/aten/src/ATen/native/cuda/IndexKernel.cu:60: lambda [](int)->auto::operator()(int)->auto: block: [28,0,0], thread: [29,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
/opt/conda/conda-bld/pytorch_1573049304260/work/aten/src/ATen/native/cuda/IndexKernel.cu:60: lambda [](int)->auto::operator()(int)->auto: block: [28,0,0], thread: [30,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
/opt/conda/conda-bld/pytorch_1573049304260/work/aten/src/ATen/native/cuda/IndexKernel.cu:60: lambda [](int)->auto::operator()(int)->auto: block: [28,0,0], thread: [31,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.

```

**Comment by Arthur151** [comment]
Actually, there is a colors  option for texture rendering in DIB renderer!
Please refer to the code!
https://github.com/NVIDIAGameWorks/kaolin/blob/ce778280f433836a44f80b2e23d6830c96aed6aa/kaolin/graphics/dib_renderer/renderer/base.py#L54
    def forward(self, points, colors, light=None, material=None, shininess=None):
The color consist of different components in different light model!
For your problem, I think Phong lighting model is the best.
https://github.com/NVIDIAGameWorks/kaolin/blob/ce778280f433836a44f80b2e23d6830c96aed6aa/kaolin/graphics/dib_renderer/renderer/base.py#L69
The color consist of :
https://github.com/NVIDIAGameWorks/kaolin/blob/ce778280f433836a44f80b2e23d6830c96aed6aa/kaolin/graphics/dib_renderer/renderer/phongrender.py#L86
Best wishes!

**Comment by tejank10** [comment]
Thanks for your reply! 

To be precise, I wanted to know how to get `uv`, `ft` and `texture` information which make up `colors`. I read a bit more about how `.obj` is read in kaolin to get this info, and figured out that there was a bug in the way `.obj` file was being read when `vt` was optional. I have submitted a PR (#105 ) regarding this. 

Cheers!

**Comment by TommyX12** [comment]
I have opened a PR (#115) to add texturing example. Stay tuned!

**Comment by Caenorst** [comment]
Hi, thank you for using Kaolin! The library went through a major rewrite with the version [0.9.0](https://github.com/NVIDIAGameWorks/kaolin/releases/tag/v0.9.0), and only the core library components we can thoroughly test and maintain are now part of this repository. Please refer to our latest documentation:
[https://kaolin.readthedocs.io/en/latest/](https://kaolin.readthedocs.io/en/latest/)

DIB-R does support any kind of attributes as input, whether it's texture or vertex colors.

Closing the bug as it is no longer relevant to this repo.
